"""
Reviewed Arabic names, each with the Latin spelling a handle is made of.

Faker's Arabic providers return tribes, trades and a few notorious families, and give names that
are not names (the first names «ماذى», «لوليا»), so the members' names are drawn from these lists
instead: common given names of the Arabic-speaking countries, by the gender the member declares,
and family names that are plain surnames. The Latin forms are the common transliterations, so a
handle reads like its owner's name.
"""

from __future__ import annotations

MALE: tuple[tuple[str, str], ...] = (
    ("محمد", "mohamed"),
    ("أحمد", "ahmed"),
    ("عمر", "omar"),
    ("علي", "ali"),
    ("يوسف", "youssef"),
    ("إبراهيم", "brahim"),
    ("خالد", "khaled"),
    ("حسن", "hassan"),
    ("حسين", "hussein"),
    ("مصطفى", "mustapha"),
    ("عبد الله", "abdallah"),
    ("عبد الرحمن", "abderrahmane"),
    ("سعيد", "said"),
    ("كريم", "karim"),
    ("طارق", "tarek"),
    ("ياسين", "yassine"),
    ("أنس", "anas"),
    ("بلال", "bilal"),
    ("هشام", "hicham"),
    ("ماجد", "majed"),
    ("نبيل", "nabil"),
    ("سليمان", "slimane"),
    ("عثمان", "othman"),
    ("زياد", "ziyad"),
    ("رياض", "riadh"),
    ("فيصل", "faisal"),
    ("سامي", "sami"),
    ("وليد", "walid"),
    ("أمين", "amine"),
    ("رشيد", "rachid"),
    ("جمال", "jamal"),
    ("إسماعيل", "ismail"),
    ("صلاح", "salah"),
    ("ماهر", "maher"),
    ("عادل", "adel"),
    ("مراد", "mourad"),
    ("لطفي", "lotfi"),
    ("نور الدين", "noureddine"),
    ("عماد", "imad"),
    ("حمزة", "hamza"),
    ("ياسر", "yasser"),
    ("بدر", "badr"),
    ("سلمان", "salman"),
    ("ناصر", "nasser"),
    ("طه", "taha"),
    ("أيمن", "ayman"),
    ("هاني", "hani"),
    ("إلياس", "elyes"),
    ("آدم", "adam"),
    ("مهدي", "mehdi"),
    ("عصام", "issam"),
    ("جلال", "jalal"),
    ("سفيان", "sofiane"),
    ("حاتم", "hatem"),
    ("أكرم", "akram"),
    ("معاذ", "moaz"),
    ("أيوب", "ayoub"),
    ("زكريا", "zakaria"),
    ("إدريس", "idris"),
    ("موسى", "moussa"),
    ("عيسى", "issa"),
    ("داود", "daoud"),
    ("سهيل", "souheil"),
    ("منير", "mounir"),
    ("فاضل", "fadel"),
    ("وسيم", "wassim"),
    ("رضا", "reda"),
)

FEMALE: tuple[tuple[str, str], ...] = (
    ("فاطمة", "fatima"),
    ("عائشة", "aicha"),
    ("مريم", "maryam"),
    ("خديجة", "khadija"),
    ("زينب", "zeineb"),
    ("آمنة", "amina"),
    ("سارة", "sara"),
    ("ليلى", "leila"),
    ("نور", "nour"),
    ("هدى", "hoda"),
    ("سلمى", "salma"),
    ("أسماء", "asma"),
    ("هاجر", "hajer"),
    ("إيمان", "imen"),
    ("رنا", "rana"),
    ("لينا", "lina"),
    ("دعاء", "doaa"),
    ("ياسمين", "yasmine"),
    ("أمل", "amal"),
    ("سعاد", "souad"),
    ("نادية", "nadia"),
    ("سمية", "soumaya"),
    ("حنان", "hanen"),
    ("منى", "mona"),
    ("ريم", "rim"),
    ("سناء", "sana"),
    ("وفاء", "wafa"),
    ("رقية", "roukaya"),
    ("بسمة", "basma"),
    ("لمياء", "lamia"),
    ("شيماء", "chaima"),
    ("آية", "aya"),
    ("جميلة", "jamila"),
    ("نجلاء", "najla"),
    ("رحمة", "rahma"),
    ("إسراء", "israa"),
    ("فرح", "farah"),
    ("ملاك", "malak"),
    ("تسنيم", "tasnim"),
    ("رزان", "razan"),
    ("لبنى", "lobna"),
    ("صفاء", "safa"),
    ("عبير", "abir"),
    ("ندى", "nada"),
    ("سهى", "suha"),
    ("هيفاء", "haifa"),
    ("أروى", "arwa"),
    ("بتول", "batoul"),
    ("مروة", "marwa"),
    ("حياة", "hayat"),
    ("كوثر", "kawthar"),
    ("أميرة", "amira"),
    ("نسرين", "nesrine"),
    ("رجاء", "rajaa"),
    ("سلوى", "salwa"),
    ("دينا", "dina"),
    ("غادة", "ghada"),
    ("سمر", "samar"),
    ("لارا", "lara"),
    ("وئام", "wiem"),
    ("أحلام", "ahlem"),
    ("رانيا", "rania"),
    ("هالة", "hala"),
)

# Family names by region, so a member's surname belongs to their country's world: a Yemeni
# family name on a Moroccan member would look invented.
_MAGHREB_WEST: tuple[tuple[str, str], ...] = (
    ("الإدريسي", "idrissi"),
    ("الفاسي", "fassi"),
    ("التازي", "tazi"),
    ("العمراني", "amrani"),
    ("الكتاني", "kettani"),
    ("السوسي", "soussi"),
    ("بن جلون", "benjelloun"),
    ("المراكشي", "marrakchi"),
    ("العلوي", "alaoui"),
    ("بن عمر", "benomar"),
    ("الشرقاوي", "cherkaoui"),
    ("البقالي", "bakkali"),
)
_ALGERIA: tuple[tuple[str, str], ...] = (
    ("بلحاج", "belhadj"),
    ("بوزيد", "bouzid"),
    ("بوعلي", "bouali"),
    ("الشريف", "cherif"),
    ("الهاشمي", "hachemi"),
    ("السعدي", "saidi"),
    ("بن عيسى", "benaissa"),
    ("بن سالم", "bensalem"),
    ("مسعودي", "messaoudi"),
    ("زروقي", "zerrouki"),
    ("بوشامة", "bouchama"),
)
_TUNISIA: tuple[tuple[str, str], ...] = (
    ("بن علي", "benali"),
    ("بن صالح", "bensalah"),
    ("بن يوسف", "benyoussef"),
    ("الطرابلسي", "trabelsi"),
    ("الشابي", "chebbi"),
    ("الفرجاني", "ferjani"),
    ("العياري", "ayari"),
    ("السلامي", "salmi"),
    ("المرزوقي", "marzouki"),
    ("بلحاج", "belhadj"),
    ("الجبالي", "jebali"),
    ("الغربي", "gharbi"),
)
_LIBYA: tuple[tuple[str, str], ...] = (
    ("الورفلي", "warfali"),
    ("السنوسي", "senoussi"),
    ("المصراتي", "misrati"),
    ("الطرابلسي", "trabelsi"),
    ("الفيتوري", "fitouri"),
    ("الزوي", "zway"),
    ("العبيدي", "obeidi"),
    ("الترهوني", "tarhouni"),
)
_MAURITANIA: tuple[tuple[str, str], ...] = (
    ("الأمين", "elamin"),
    ("الطالب", "taleb"),
    ("السالك", "salek"),
    ("الحسن", "elhassan"),
    ("الشيخ", "cheikh"),
    ("المختار", "elmokhtar"),
    ("سيدي", "sidi"),
)
_EGYPT: tuple[tuple[str, str], ...] = (
    ("السيد", "elsayed"),
    ("عبد الحميد", "abdelhamid"),
    ("فهمي", "fahmy"),
    ("عبد الرحمن", "abdelrahman"),
    ("حسنين", "hassanein"),
    ("الشافعي", "shafei"),
    ("منصور", "mansour"),
    ("زكي", "zaki"),
    ("سالم", "salem"),
    ("عبد العزيز", "abdelaziz"),
    ("رمضان", "ramadan"),
    ("شاكر", "shaker"),
)
_SUDAN: tuple[tuple[str, str], ...] = (
    ("الطيب", "eltayeb"),
    ("المهدي", "mahdi"),
    ("عثمان", "osman"),
    ("الأمين", "elamin"),
    ("الفاضل", "elfadil"),
    ("الخضر", "elkhidir"),
    ("إدريس", "idris"),
    ("حمد", "hamad"),
)
_LEVANT: tuple[tuple[str, str], ...] = (
    ("الحداد", "haddad"),
    ("النجار", "najjar"),
    ("الخياط", "khayat"),
    ("الحلبي", "halabi"),
    ("الشامي", "chami"),
    ("الخطيب", "khatib"),
    ("خوري", "khoury"),
    ("سلام", "salam"),
    ("الدمشقي", "dimashqi"),
    ("الحمصي", "homsi"),
    ("الأيوبي", "ayoubi"),
    ("القباني", "qabbani"),
    ("الكيلاني", "kilani"),
    ("الرفاعي", "rifai"),
    ("العمري", "omari"),
    ("البكري", "bakri"),
    ("الزين", "zein"),
    ("الدباغ", "debbagh"),
)
_PALESTINE_JORDAN: tuple[tuple[str, str], ...] = (
    ("البرغوثي", "barghouti"),
    ("الخالدي", "khalidi"),
    ("النابلسي", "nabulsi"),
    ("الخطيب", "khatib"),
    ("الحسيني", "husseini"),
    ("المجالي", "majali"),
    ("الطراونة", "tarawneh"),
    ("العمري", "omari"),
    ("الكيلاني", "kilani"),
    ("الزعبي", "zoubi"),
    ("الحجازي", "hijazi"),
)
_IRAQ: tuple[tuple[str, str], ...] = (
    ("البغدادي", "baghdadi"),
    ("الجبوري", "jabouri"),
    ("الساعدي", "saadi"),
    ("البصري", "basri"),
    ("الموصلي", "mawsili"),
    ("العبيدي", "obeidi"),
    ("الجابري", "jabri"),
    ("الحسني", "hasani"),
    ("الربيعي", "rubaie"),
    ("التميمي", "tamimi"),
    ("العزاوي", "azzawi"),
)
_GULF: tuple[tuple[str, str], ...] = (
    ("القحطاني", "qahtani"),
    ("العتيبي", "otaibi"),
    ("الحربي", "harbi"),
    ("الزهراني", "zahrani"),
    ("الغامدي", "ghamdi"),
    ("الشمري", "shammari"),
    ("الدوسري", "dosari"),
    ("المطيري", "mutairi"),
    ("الكعبي", "kaabi"),
    ("النعيمي", "nuaimi"),
    ("المنصوري", "mansouri"),
    ("الراشد", "rashid"),
    ("الهاشمي", "hashimi"),
    ("المري", "marri"),
)
_SAUDI: tuple[tuple[str, str], ...] = (*_GULF, ("الحجازي", "hijazi"), ("العمري", "omari"))
_OMAN: tuple[tuple[str, str], ...] = (
    ("البلوشي", "balushi"),
    ("الحارثي", "harthi"),
    ("الكندي", "kindi"),
    ("الهنائي", "hinai"),
    ("الفارسي", "farsi"),
    ("الرواحي", "rawahi"),
    ("السعدي", "saadi"),
)
_YEMEN: tuple[tuple[str, str], ...] = (
    ("الحميري", "himyari"),
    ("الصنعاني", "sanani"),
    ("العريقي", "areeqi"),
    ("الأهدل", "ahdal"),
    ("باوزير", "bawazir"),
    ("العولقي", "awlaqi"),
    ("الشرعبي", "sharabi"),
)
_HORN: tuple[tuple[str, str], ...] = (
    ("عبدي", "abdi"),
    ("فارح", "farah"),
    ("ورسمه", "warsame"),
    ("آدم", "adam"),
    ("حرسي", "hersi"),
    ("يوسف", "yousuf"),
    ("عثمان", "osman"),
)
_COMOROS: tuple[tuple[str, str], ...] = (
    ("سعيد", "said"),
    ("عبد الله", "abdallah"),
    ("محمد", "mohamed"),
    ("علي", "ali"),
    ("إبراهيم", "ibrahim"),
    ("حسن", "hassan"),
)

FAMILY_BY_COUNTRY: dict[str, tuple[tuple[str, str], ...]] = {
    "MA": _MAGHREB_WEST,
    "DZ": _ALGERIA,
    "TN": _TUNISIA,
    "LY": _LIBYA,
    "MR": _MAURITANIA,
    "EG": _EGYPT,
    "SD": _SUDAN,
    "SY": _LEVANT,
    "LB": _LEVANT,
    "JO": _PALESTINE_JORDAN,
    "PS": _PALESTINE_JORDAN,
    "IQ": _IRAQ,
    "SA": _SAUDI,
    "AE": _GULF,
    "QA": _GULF,
    "KW": _GULF,
    "BH": _GULF,
    "OM": _OMAN,
    "YE": _YEMEN,
    "SO": _HORN,
    "DJ": _HORN,
    "KM": _COMOROS,
}
# Every family name of every region, once.
FAMILY: tuple[tuple[str, str], ...] = tuple(
    dict.fromkeys(name for names in FAMILY_BY_COUNTRY.values() for name in names)
)
