"""
Reviewed Arabic names, each with the Latin spelling a handle is made of.

Faker's Arabic providers return tribes, trades and a few notorious families, and give names that
are not names (the first names «ماذى», «لوليا»), so the members' names are drawn from these lists
instead: common given names of the Arabic-speaking countries, by the gender the member declares,
and family names that are plain surnames. The Latin forms are the common transliterations, so a
handle reads like its owner's name.
"""

from __future__ import annotations

MALE: tuple[tuple[str, str], ...] = (
    ("محمد", "mohamed"),
    ("أحمد", "ahmed"),
    ("عمر", "omar"),
    ("علي", "ali"),
    ("يوسف", "youssef"),
    ("إبراهيم", "brahim"),
    ("خالد", "khaled"),
    ("حسن", "hassan"),
    ("حسين", "hussein"),
    ("مصطفى", "mustapha"),
    ("عبد الله", "abdallah"),
    ("عبد الرحمن", "abderrahmane"),
    ("سعيد", "said"),
    ("كريم", "karim"),
    ("طارق", "tarek"),
    ("ياسين", "yassine"),
    ("أنس", "anas"),
    ("بلال", "bilal"),
    ("هشام", "hicham"),
    ("ماجد", "majed"),
    ("نبيل", "nabil"),
    ("سليمان", "slimane"),
    ("عثمان", "othman"),
    ("زياد", "ziyad"),
    ("رياض", "riadh"),
    ("فيصل", "faisal"),
    ("سامي", "sami"),
    ("وليد", "walid"),
    ("أمين", "amine"),
    ("رشيد", "rachid"),
    ("جمال", "jamal"),
    ("إسماعيل", "ismail"),
    ("صلاح", "salah"),
    ("ماهر", "maher"),
    ("عادل", "adel"),
    ("مراد", "mourad"),
    ("لطفي", "lotfi"),
    ("نور الدين", "noureddine"),
    ("عماد", "imad"),
    ("حمزة", "hamza"),
    ("ياسر", "yasser"),
    ("بدر", "badr"),
    ("سلمان", "salman"),
    ("ناصر", "nasser"),
    ("طه", "taha"),
    ("أيمن", "ayman"),
    ("هاني", "hani"),
    ("إلياس", "elyes"),
    ("آدم", "adam"),
    ("مهدي", "mehdi"),
    ("عصام", "issam"),
    ("جلال", "jalal"),
    ("سفيان", "sofiane"),
    ("حاتم", "hatem"),
    ("أكرم", "akram"),
    ("معاذ", "moaz"),
    ("أيوب", "ayoub"),
    ("زكريا", "zakaria"),
    ("إدريس", "idris"),
    ("موسى", "moussa"),
    ("عيسى", "issa"),
    ("داود", "daoud"),
    ("سهيل", "souheil"),
    ("منير", "mounir"),
    ("فاضل", "fadel"),
    ("وسيم", "wassim"),
    ("رضا", "reda"),
)

FEMALE: tuple[tuple[str, str], ...] = (
    ("فاطمة", "fatima"),
    ("عائشة", "aicha"),
    ("مريم", "maryam"),
    ("خديجة", "khadija"),
    ("زينب", "zeineb"),
    ("آمنة", "amina"),
    ("سارة", "sara"),
    ("ليلى", "leila"),
    ("نور", "nour"),
    ("هدى", "hoda"),
    ("سلمى", "salma"),
    ("أسماء", "asma"),
    ("هاجر", "hajer"),
    ("إيمان", "imen"),
    ("رنا", "rana"),
    ("لينا", "lina"),
    ("دعاء", "doaa"),
    ("ياسمين", "yasmine"),
    ("أمل", "amal"),
    ("سعاد", "souad"),
    ("نادية", "nadia"),
    ("سمية", "soumaya"),
    ("حنان", "hanen"),
    ("منى", "mona"),
    ("ريم", "rim"),
    ("سناء", "sana"),
    ("وفاء", "wafa"),
    ("رقية", "roukaya"),
    ("بسمة", "basma"),
    ("لمياء", "lamia"),
    ("شيماء", "chaima"),
    ("آية", "aya"),
    ("جميلة", "jamila"),
    ("نجلاء", "najla"),
    ("رحمة", "rahma"),
    ("إسراء", "israa"),
    ("فرح", "farah"),
    ("ملاك", "malak"),
    ("تسنيم", "tasnim"),
    ("رزان", "razan"),
    ("لبنى", "lobna"),
    ("صفاء", "safa"),
    ("عبير", "abir"),
    ("ندى", "nada"),
    ("سهى", "suha"),
    ("هيفاء", "haifa"),
    ("أروى", "arwa"),
    ("بتول", "batoul"),
    ("مروة", "marwa"),
    ("حياة", "hayat"),
    ("كوثر", "kawthar"),
    ("أميرة", "amira"),
    ("نسرين", "nesrine"),
    ("رجاء", "rajaa"),
    ("سلوى", "salwa"),
    ("دينا", "dina"),
    ("غادة", "ghada"),
    ("سمر", "samar"),
    ("لارا", "lara"),
    ("وئام", "wiem"),
    ("أحلام", "ahlem"),
    ("رانيا", "rania"),
    ("هالة", "hala"),
)

FAMILY: tuple[tuple[str, str], ...] = (
    ("الحداد", "haddad"),
    ("النجار", "najjar"),
    ("الخياط", "khayat"),
    ("الحلبي", "halabi"),
    ("الشامي", "chami"),
    ("المصري", "masri"),
    ("البغدادي", "baghdadi"),
    ("الحجازي", "hijazi"),
    ("القحطاني", "qahtani"),
    ("العتيبي", "otaibi"),
    ("الحربي", "harbi"),
    ("الزهراني", "zahrani"),
    ("الغامدي", "ghamdi"),
    ("الشمري", "shammari"),
    ("الدوسري", "dosari"),
    ("المطيري", "mutairi"),
    ("الكعبي", "kaabi"),
    ("النعيمي", "nuaimi"),
    ("المنصوري", "mansouri"),
    ("الجبوري", "jabouri"),
    ("الساعدي", "saadi"),
    ("البصري", "basri"),
    ("الخطيب", "khatib"),
    ("البرغوثي", "barghouti"),
    ("الخالدي", "khalidi"),
    ("النابلسي", "nabulsi"),
    ("الصالحي", "salhi"),
    ("بن علي", "benali"),
    ("بن صالح", "bensalah"),
    ("بن يوسف", "benyoussef"),
    ("بن عمر", "benomar"),
    ("الطرابلسي", "trabelsi"),
    ("الشابي", "chebbi"),
    ("الفرجاني", "ferjani"),
    ("العياري", "ayari"),
    ("السلامي", "salmi"),
    ("بلحاج", "belhadj"),
    ("بوزيد", "bouzid"),
    ("الهاشمي", "hachemi"),
    ("الإدريسي", "idrissi"),
    ("الفاسي", "fassi"),
    ("التازي", "tazi"),
    ("العمراني", "amrani"),
    ("الكتاني", "kettani"),
    ("السوسي", "soussi"),
    ("بن جلون", "benjelloun"),
    ("المراكشي", "marrakchi"),
    ("الأمين", "elamin"),
    ("الطيب", "eltayeb"),
    ("الحميري", "himyari"),
    ("الصنعاني", "sanani"),
    ("السيد", "elsayed"),
    ("عبد الحميد", "abdelhamid"),
    ("فهمي", "fahmy"),
    ("خوري", "khoury"),
    ("سلام", "salam"),
    ("الدمشقي", "dimashqi"),
    ("الحمصي", "homsi"),
    ("الأيوبي", "ayoubi"),
    ("القباني", "qabbani"),
    ("العلوي", "alaoui"),
    ("الرفاعي", "rifai"),
    ("المهدي", "mahdi"),
    ("الجزائري", "djazairi"),
    ("التونسي", "tounsi"),
    ("المغربي", "maghribi"),
    ("الموصلي", "mawsili"),
    ("العمري", "omari"),
    ("البكري", "bakri"),
    ("الزين", "zein"),
    ("الشريف", "cherif"),
    ("الكيلاني", "kilani"),
    ("الدباغ", "debbagh"),
    ("المرزوقي", "marzouki"),
    ("الورفلي", "warfali"),
    ("السنوسي", "senoussi"),
    ("بوعلي", "bouali"),
    ("بن سالم", "bensalem"),
    ("العبيدي", "obeidi"),
    ("الحسني", "hasani"),
    ("الجابري", "jabri"),
    ("الراشد", "rashid"),
    ("الفارسي", "farsi"),
    ("السعدي", "saidi"),
    ("الكبير", "kabir"),
    ("المنسي", "mansi"),
)
