import path from 'node:path';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    alias: { '@': path.resolve(import.meta.dirname, 'src') },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.test.{ts,tsx}'],
    restoreMocks: true,
    // The gallery renders the shell eleven times; on a busy CI agent five seconds is too tight.
    testTimeout: 15_000,
    unstubEnvs: true,
    unstubGlobals: true,
    coverage: {
      provider: 'v8',
      include: ['src/**/*.{ts,tsx}'],
      // Reasons for every exclusion (AGENTS.md: an exclusion needs a written reason):
      // - tests and the shared test setup are not product code;
      // - schema.d.ts is generated by openapi-typescript from the API's OpenAPI
      //   document and holds types only, no statements to execute.
      exclude: ['src/**/*.test.{ts,tsx}', 'src/test/**', 'src/lib/api/schema.d.ts'],
      reporter: ['text', 'html', 'json-summary', 'lcov', 'cobertura'],
      reportsDirectory: './coverage',
      thresholds: {
        lines: 100,
        branches: 100,
        functions: 100,
        statements: 100,
      },
    },
  },
});
