import createClient, { type Client, type ClientOptions } from 'openapi-fetch';
import { apiOrigin } from '@/lib/site';
import type { paths } from './schema';

export type ApiClient = Client<paths>;

export type ApiClientOptions = Omit<ClientOptions, 'credentials'>;

/**
 * The API client, typed from the API's own OpenAPI document (src/lib/api/schema.d.ts,
 * generated by `pnpm gen:api`). The session is an httpOnly cookie on the shared
 * parent domain, so every request carries credentials.
 */
export function createApiClient(options: ApiClientOptions = {}): ApiClient {
  return createClient<paths>({ baseUrl: apiOrigin(), ...options, credentials: 'include' });
}

export const api: ApiClient = createApiClient();
