/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness
     * @description Report that the process is up and serving.
     *
     *     Touches no dependency, so it stays cheap enough for a per-second probe and
     *     answers even when the database is down.
     */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness
     * @description Report whether this process can serve a request, which needs the database.
     *
     *     The check is bounded by the connect timeout, so a database that is down or
     *     hangs answers 503 `degraded` quickly instead of holding the request.
     */
    get: operations['readiness_health_ready_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create an account with an e-mail address and a password
     * @description Create the account, sign it in, and mail a verification link.
     *
     *     The new account can be used at once; its address stays unverified until the
     *     link is followed. Rate limited per IP and per e-mail address. A mail that
     *     cannot be sent never fails the sign-up.
     */
    post: operations['signup_auth_signup_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign in with an e-mail address and a password
     * @description Start a session.
     *
     *     A wrong address and a wrong password answer the same 401. Rate limited per IP
     *     and per e-mail address, counting failed attempts, before the password is checked.
     */
    post: operations['login_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * End the current session
     * @description End the session and clear the cookie. Safe to repeat, and to call with no session.
     */
    post: operations['logout_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The signed-in account
     * @description Return the caller's own account. The private profile fields are not part of it.
     */
    get: operations['me_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Which ways of signing in are available
     * @description Whether password and Google sign-in can be used, for the sign-in page to show.
     */
    get: operations['providers_auth_providers_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm an e-mail address with the mailed link's token
     * @description Mark the address verified. The token works once; any bad token answers the same 400.
     *
     *     The caller needs no session: whoever holds the token read the mail.
     */
    post: operations['verify_email_auth_verify_email_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/resend-verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mail the verification link again
     * @description Answer 202 whether or not the address has an unverified account.
     *
     *     Rate limited per IP and per address. A new link cancels the earlier one.
     */
    post: operations['resend_verification_auth_resend_verification_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/forgot-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mail a password reset link
     * @description Answer 202 whether or not the address has an account.
     *
     *     Rate limited per IP and per address. A new link cancels the earlier one. The
     *     mail is sent after the answer, so the time it takes says nothing either.
     */
    post: operations['forgot_password_auth_forgot_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Choose a new password with the mailed link's token
     * @description Set the new password and end every other session of the account.
     *
     *     The token works once. Following it also proves the address, so it is marked
     *     verified. The caller is not signed in by it: they sign in with the new password.
     */
    post: operations['reset_password_auth_reset_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/google/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Send the browser to Google to sign in
     * @description Begin the authorization code flow with PKCE (S256), a state and a nonce.
     *
     *     Redirects to Google. The state, the code verifier and the nonce are kept on
     *     the server for GOOGLE_STATE_TTL_SECONDS; a cookie ties them to this browser.
     */
    get: operations['start_auth_google_start_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/google/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Where Google sends the browser back
     * @description Finish the sign-in: check the state, exchange the code, validate the ID token.
     *
     *     Then link or create the account, start a session and redirect to the web app.
     */
    get: operations['callback_auth_google_callback_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The caller's profile
     * @description Return the caller's own profile, empty answers as `unknown`.
     *
     *     The religious background, the gender and the age range are private: this
     *     route and the account export are the only places they are ever returned.
     */
    get: operations['get_profile_profile_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Change some answers of the caller's profile
     * @description Change the fields sent and no others.
     *
     *     Enums are validated; a null is refused (send `unknown` to clear an answer).
     *     The three consent switches change through `POST /consents` only.
     */
    patch: operations['patch_profile_profile_patch'];
    trace?: never;
  };
  '/consents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record an answer to a consent question
     * @description Append the answer to the user's consent history, and update the matching switch.
     *
     *     A consent is withdrawn by recording the same kind with `granted` false. The
     *     history is never edited.
     */
    post: operations['post_consent_consents_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/account/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download everything the account owns
     * @description Return the account, its profile, consents, linked identities and sessions as JSON.
     */
    get: operations['export_account_account_export_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/account': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete the account and everything it owns
     * @description Delete the user, their profile, consents, linked identities and every session.
     *
     *     Idempotent: without a valid session there is nothing left to delete, and the
     *     answer is the same 204 that clears the cookie.
     */
    delete: operations['delete_account_account_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/geo/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search places by Arabic or Latin name
     * @description Return places whose name matches `q`, in Arabic or in Latin letters.
     *
     *     Exact matches come first, then names that start with `q`, each by
     *     population, then similar names. `label` is the Arabic name when there is
     *     one. The text is matched without regard to case, accents, Arabic vowel
     *     marks or the alef, ta marbuta and ya variants.
     */
    get: operations['search_geo_search_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/geo/reverse': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The populated place nearest to a point
     * @description Return the nearest populated place within `radius_m`, with its region and country.
     *
     *     It labels an approximate location: send the rounded point (see
     *     `src/geo/privacy.py`), never the exact one of a photo, and keep the answer
     *     to the place found. Nothing is returned when no populated place is in range.
     */
    get: operations['reverse_geo_reverse_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/geo/countries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Countries
     * @description Return every country, with its Arabic name when GeoNames has one.
     */
    get: operations['countries_geo_countries_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scripture/quran/{surah}/{ayah}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * One verse of the Quran
     * @description Return a verse of quranpedia's mushaf 2 exactly as stored, with its hash and source.
     */
    get: operations['quran_verse_scripture_quran__surah___ayah__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scripture/hadith/{collection}/{number}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * One hadith
     * @description Return a hadith exactly as stored, with its spans, its ruling and its eligibility.
     */
    get: operations['hadith_scripture_hadith__collection___number__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/client-errors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Report errors a page saw
     * @description Accept a page's error reports and forward them to GlitchTip, cleaned.
     *
     *     Answers 204 whether or not anything is forwarded.
     */
    post: operations['report_client_errors_client_errors_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/consent/policy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The categories to choose between and the re-ask interval
     * @description Return the current policy.
     *
     *     The policy is its version, each category with its Arabic title and description, and the
     *     number of days after which a choice lapses and the visitor is asked again.
     */
    get: operations['get_policy_consent_policy_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/consent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record a cookie choice
     * @description Append the choice and return the consent id with what is in force.
     *
     *     The first call has no `consent_id`; keep the one returned in a first-party cookie and send
     *     it with every later choice, so they are one history. Choosing again is a new record, never
     *     an edit. The user agent is reduced to its browser family and no address is kept.
     */
    post: operations['post_consent_consent_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/consent/{consent_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The choice in force for a consent id
     * @description Return what the id's latest choice allows now.
     *
     *     While the choice is current its categories are the ones chosen; once the policy changed or
     *     the re-ask interval passed, `reask` is true and only the necessary category is on. An id the
     *     server never issued is a 404.
     */
    get: operations['get_consent_consent__consent_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sitemap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Every section's pages
     * @description List the sections that are advertised, each with its pages and their last change.
     *
     *     A section whose feature is switched off is not listed, and a section with nothing to list
     *     has no pages.
     */
    get: operations['sitemap_index_sitemap_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sitemap/{section}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * One page of a section
     * @description List one page of a section, in a stable order.
     *
     *     A page past the last is empty. A section whose feature is off is a 404, like its pages.
     */
    get: operations['sitemap_section_sitemap__section__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AccountExport
     * @description Everything the account owns so far, for its owner.
     *
     *     A table that gets a user id later must be added here and to the deletion in
     *     `account_service`; a test fails when a table references `users` without a cascade.
     */
    AccountExport: {
      /**
       * Exported At
       * Format: date-time
       */
      exported_at: string;
      user: components['schemas']['UserExport'];
      /** Oauth Accounts */
      oauth_accounts: components['schemas']['OAuthAccountExport'][];
      /** Sessions */
      sessions: components['schemas']['SessionExport'][];
      profile: components['schemas']['ProfileOut'];
      /** Consents */
      consents: components['schemas']['ConsentOut'][];
      /** Cookie Consents */
      cookie_consents: components['schemas']['CookieConsentExport'][];
    };
    /**
     * AdminArea
     * @description The first-level administrative division (region, governorate, state) of a place.
     */
    AdminArea: {
      /** Geoname Id */
      geoname_id: number;
      /** Name */
      name: string;
      /** Name Ar */
      name_ar: string | null;
      /** Label */
      label: string;
    };
    /**
     * AgeRange
     * @enum {string}
     */
    AgeRange: 'under_13' | '13_17' | '18_24' | '25_39' | '40_59' | '60_plus' | 'unknown';
    /** ChapterOut */
    ChapterOut: {
      /** Book Number */
      book_number: number | null;
      /** Book Name */
      book_name: string | null;
      /** Number In Book */
      number_in_book: number | null;
    };
    /**
     * ClientBreadcrumb
     * @description One thing that happened before the error, as the page remembers it.
     */
    ClientBreadcrumb: {
      /**
       * Category
       * @default log
       */
      category: string;
      /**
       * Level
       * @default info
       * @enum {string}
       */
      level: 'debug' | 'info' | 'warning' | 'error';
      /** Message */
      message: string;
      /** Timestamp */
      timestamp?: number | null;
    };
    /**
     * ClientReport
     * @description One error or log record from the browser.
     */
    ClientReport: {
      /**
       * Kind
       * @default error
       * @enum {string}
       */
      kind: 'error' | 'log';
      /**
       * Level
       * @default error
       * @enum {string}
       */
      level: 'warning' | 'error' | 'fatal';
      /** Message */
      message: string;
      /** Name */
      name?: string | null;
      /** Stack */
      stack?: string | null;
      /** Url */
      url?: string | null;
      /**
       * Handled
       * @default true
       */
      handled: boolean;
      /** Context */
      context?: {
        [key: string]: string | number | boolean | null;
      } | null;
      /** Breadcrumbs */
      breadcrumbs?: components['schemas']['ClientBreadcrumb'][];
      /** Release */
      release?: string | null;
    };
    /**
     * ClientReportBatch
     * @description A page's pending reports, flushed together.
     */
    ClientReportBatch: {
      /** Items */
      items: components['schemas']['ClientReport'][];
    };
    /** CollectionOut */
    CollectionOut: {
      /** Slug */
      slug: string;
      /** Name Ar */
      name_ar: string;
      /** Source Dataset */
      source_dataset: string;
      /** Source Url */
      source_url: string;
      /** Licence */
      licence: string;
      /** Version */
      version: string;
    };
    /**
     * ConsentCategories
     * @description Each category and whether it is on. The necessary one always is.
     */
    ConsentCategories: {
      /**
       * Necessary
       * @default true
       * @constant
       */
      necessary: true;
      /** Analytics */
      analytics: boolean;
      /** Behaviour */
      behaviour: boolean;
    };
    /** ConsentCategoryOut */
    ConsentCategoryOut: {
      /**
       * Key
       * @enum {string}
       */
      key: 'necessary' | 'analytics' | 'behaviour';
      /** Required */
      required: boolean;
      /** Title */
      title: string;
      /** Description */
      description: string;
    };
    /** ConsentIn */
    ConsentIn: {
      kind: components['schemas']['ConsentKind'];
      /** Version */
      version: string;
      /** Granted */
      granted: boolean;
    };
    /**
     * ConsentKind
     * @enum {string}
     */
    ConsentKind: 'terms' | 'photo_storage' | 'personalization' | 'memory';
    /** ConsentOut */
    ConsentOut: {
      kind: components['schemas']['ConsentKind'];
      /** Version */
      version: string;
      /** Granted */
      granted: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ConsentPolicyOut
     * @description What a visitor is asked, and when they are asked again.
     */
    ConsentPolicyOut: {
      /** Policy Version */
      policy_version: string;
      /** Reask Days */
      reask_days: number;
      /** Categories */
      categories: components['schemas']['ConsentCategoryOut'][];
    };
    /**
     * CookieConsentExport
     * @description One recorded choice, as the account export shows it.
     */
    CookieConsentExport: {
      /**
       * Consent Id
       * Format: uuid
       */
      consent_id: string;
      /** Policy Version */
      policy_version: string;
      /** Necessary */
      necessary: boolean;
      /** Analytics */
      analytics: boolean;
      /** Behaviour */
      behaviour: boolean;
      /** User Agent Family */
      user_agent_family: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * CookieConsentIn
     * @description A choice, as the visitor made it.
     *
     *     `consent_id` is the id the server gave this browser before; leave it out on the first
     *     choice. An id the server does not know is not adopted: a new one is made and returned.
     *     `policy_version` is the version of the text the visitor was shown; leave it out for the
     *     current one. The two flags must be JSON booleans.
     */
    CookieConsentIn: {
      /** Consent Id */
      consent_id?: string | null;
      /** Policy Version */
      policy_version?: string | null;
      /**
       * Necessary
       * @default true
       * @constant
       */
      necessary: true;
      /** Analytics */
      analytics: boolean;
      /** Behaviour */
      behaviour: boolean;
    };
    /**
     * CookieConsentOut
     * @description The choice in force for one consent id.
     *
     *     `categories` is what may run now: the recorded choice while it holds, and only the
     *     necessary category once it lapsed. It lapses when the policy version changed or
     *     `expires_at` has passed; `reask` is then true and the visitor must be asked again.
     */
    CookieConsentOut: {
      /**
       * Consent Id
       * Format: uuid
       */
      consent_id: string;
      /** Policy Version */
      policy_version: string;
      /**
       * Decided At
       * Format: date-time
       */
      decided_at: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /** Reask */
      reask: boolean;
      categories: components['schemas']['ConsentCategories'];
    };
    /**
     * Country
     * @description A country, from the GeoNames country information.
     */
    Country: {
      /** Iso2 */
      iso2: string;
      /** Iso3 */
      iso3: string | null;
      /** Name */
      name: string;
      /** Name Ar */
      name_ar: string | null;
      /** Label */
      label: string;
      /** Capital */
      capital: string | null;
      /** Continent */
      continent: string | null;
      /** Flag Emoji */
      flag_emoji: string | null;
      /** Population */
      population: number | null;
    };
    /**
     * CountryRef
     * @description The country of a place.
     */
    CountryRef: {
      /** Iso2 */
      iso2: string;
      /** Name */
      name: string;
      /** Name Ar */
      name_ar: string | null;
      /** Label */
      label: string;
    };
    /**
     * EmailIn
     * @description An address, for the routes that mail a link to it.
     */
    EmailIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /**
     * ErrorCode
     * @description The stable error codes. A code is never renamed or reused.
     * @enum {string}
     */
    ErrorCode:
      | 'BAD_REQUEST'
      | 'UNAUTHORIZED'
      | 'FORBIDDEN'
      | 'NOT_FOUND'
      | 'METHOD_NOT_ALLOWED'
      | 'CONFLICT'
      | 'PAYLOAD_TOO_LARGE'
      | 'VALIDATION_ERROR'
      | 'RATE_LIMITED'
      | 'INTERNAL_ERROR'
      | 'SERVICE_UNAVAILABLE'
      | 'HTTP_ERROR'
      | 'INVALID_CREDENTIALS'
      | 'EMAIL_TAKEN'
      | 'ACCOUNT_DISABLED'
      | 'EMAIL_NOT_VERIFIED'
      | 'INVALID_TOKEN'
      | 'ORIGIN_NOT_ALLOWED'
      | 'CONSENT_NOT_ALLOWED'
      | 'GOOGLE_NOT_CONFIGURED';
    /**
     * ErrorResponse
     * @description The body of every error response.
     */
    ErrorResponse: {
      error: components['schemas']['ErrorCode'];
      /** Detail */
      detail: string;
      /** Fields */
      fields?: components['schemas']['FieldError'][] | null;
    };
    /**
     * FieldError
     * @description One rejected field of a request: where it is and why it was refused.
     */
    FieldError: {
      /** Loc */
      loc: (string | number)[];
      /** Message */
      message: string;
      /** Type */
      type: string;
    };
    /**
     * Gender
     * @enum {string}
     */
    Gender: 'man' | 'woman' | 'unknown';
    /**
     * GeoJsonPoint
     * @description A GeoJSON Point (RFC 7946): `coordinates` is [longitude, latitude].
     */
    GeoJsonPoint: {
      /**
       * Type
       * @default Point
       * @constant
       */
      type: 'Point';
      /**
       * Coordinates
       * @description [longitude, latitude]
       */
      coordinates: [number, number];
    };
    /**
     * Goal
     * @description Why the user is here (master prompt v2, section 5); several may be chosen.
     * @enum {string}
     */
    Goal:
      | 'discover_islam'
      | 'reflection'
      | 'learn_quran_sunnah'
      | 'live_values'
      | 'research'
      | 'teaching'
      | 'curiosity';
    /** GradeOut */
    GradeOut: {
      /** Name */
      name: string;
      /** Grade */
      grade: string;
    };
    /**
     * HadithClassification
     * @description An editor's reading of a dorar.net ruling; only the first two make a hadith evidence.
     * @enum {string}
     */
    HadithClassification: 'صحيح' | 'حسن' | 'ضعيف' | 'موضوع' | 'مختلف_فيه';
    /** HadithLinks */
    HadithLinks: {
      /**
       * Dorar Verification
       * @description A dorar.net search for this hadith («تحقق في الدرر»)
       */
      dorar_verification: string;
    };
    /** HadithOut */
    HadithOut: {
      collection: components['schemas']['CollectionOut'];
      /**
       * Number
       * @description As the dataset numbers it
       */
      number: string;
      /** Arabic Number */
      arabic_number: string | null;
      chapter: components['schemas']['ChapterOut'] | null;
      /**
       * Text
       * @description Exactly as stored, invisible direction marks included
       */
      text: string;
      /**
       * Sha256
       * @description SHA-256 of the UTF-8 bytes of `text`
       */
      sha256: string;
      /**
       * Spans
       * @description Positions in `text`, counted in Unicode code points (not UTF-16 units); their slices join back into it
       */
      spans: components['schemas']['SpanOut'][];
      /**
       * Informational Grades
       * @description The dataset's grades as given; informational only, never decide eligibility
       */
      informational_grades: components['schemas']['GradeOut'][] | null;
      /** @description The editor-recorded dorar.net ruling in force */
      ruling: components['schemas']['RulingOut'] | null;
      /**
       * Eligible
       * @description Whether the ruling in force is صحيح or حسن
       */
      eligible: boolean;
      links: components['schemas']['HadithLinks'];
      /**
       * Status
       * @default local_corpus
       * @constant
       */
      status: 'local_corpus';
    };
    /**
     * KnowledgeLevel
     * @enum {string}
     */
    KnowledgeLevel: 'new' | 'general' | 'advanced' | 'specialist' | 'unknown';
    /** Liveness */
    Liveness: {
      /**
       * Status
       * @constant
       */
      status: 'ok';
    };
    /** LoginIn */
    LoginIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /**
     * NearbyPlace
     * @description The populated place nearest to a point.
     */
    NearbyPlace: {
      /** Geoname Id */
      geoname_id: number;
      /** Name */
      name: string;
      /** Name Ar */
      name_ar: string | null;
      /** Label */
      label: string;
      /** Feature Class */
      feature_class: string | null;
      /** Feature Code */
      feature_code: string | null;
      /** Population */
      population: number | null;
      /** Latitude */
      latitude: number;
      /** Longitude */
      longitude: number;
      location: components['schemas']['GeoJsonPoint'];
      /**
       * Distance M
       * @description Metres from the point, on the ellipsoid
       */
      distance_m: number;
    };
    /** OAuthAccountExport */
    OAuthAccountExport: {
      /** Provider */
      provider: string;
      /** Subject */
      subject: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * PlaceHit
     * @description A place that matched a search, with its region and country to tell namesakes apart.
     */
    PlaceHit: {
      /** Geoname Id */
      geoname_id: number;
      /** Name */
      name: string;
      /** Name Ar */
      name_ar: string | null;
      /** Label */
      label: string;
      /** Feature Class */
      feature_class: string | null;
      /** Feature Code */
      feature_code: string | null;
      /** Population */
      population: number | null;
      /** Latitude */
      latitude: number;
      /** Longitude */
      longitude: number;
      location: components['schemas']['GeoJsonPoint'];
      admin_area: components['schemas']['AdminArea'] | null;
      country: components['schemas']['CountryRef'] | null;
    };
    /** ProfileOut */
    ProfileOut: {
      /** Goals */
      goals: components['schemas']['Goal'][];
      knowledge_level: components['schemas']['KnowledgeLevel'];
      age_range: components['schemas']['AgeRange'];
      religious_background: components['schemas']['ReligiousBackground'];
      gender: components['schemas']['Gender'];
      /** Language */
      language: string;
      /** Personalization Enabled */
      personalization_enabled: boolean;
      /** Memory Enabled */
      memory_enabled: boolean;
      /** Photo Storage Consent */
      photo_storage_consent: boolean;
      theme: components['schemas']['Theme'];
      /** Sound Enabled */
      sound_enabled: boolean;
      /** Consent Version */
      consent_version: string | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ProfilePatch
     * @description The fields a user may change, any of them, alone.
     *
     *     The three consent switches are not here: they change only through
     *     `POST /consents`, which records the answer. A field sent as null is refused;
     *     to clear an answer, send `unknown` (or `[]` for the goals).
     */
    ProfilePatch: {
      /** Goals */
      goals?: components['schemas']['Goal'][] | null;
      knowledge_level?: components['schemas']['KnowledgeLevel'] | null;
      age_range?: components['schemas']['AgeRange'] | null;
      religious_background?: components['schemas']['ReligiousBackground'] | null;
      gender?: components['schemas']['Gender'] | null;
      /** Language */
      language?: string | null;
      theme?: components['schemas']['Theme'] | null;
      /** Sound Enabled */
      sound_enabled?: boolean | null;
    };
    /** ProviderOut */
    ProviderOut: {
      /**
       * Id
       * @enum {string}
       */
      id: 'password' | 'google';
      /** Available */
      available: boolean;
    };
    /** ProvidersOut */
    ProvidersOut: {
      /** Providers */
      providers: components['schemas']['ProviderOut'][];
    };
    /** QuranLinks */
    QuranLinks: {
      /** Quranpedia */
      quranpedia: string;
    };
    /** QuranSource */
    QuranSource: {
      /**
       * Name
       * @default quranpedia.net
       * @constant
       */
      name: 'quranpedia.net';
      /**
       * Url
       * @default https://quranpedia.net
       */
      url: string;
      /**
       * Mushaf Id
       * @default 2
       */
      mushaf_id: number;
      /**
       * Mushaf Name
       * @default مصحف حفص نسخة نصية
       */
      mushaf_name: string;
      /** Quranpedia Ayah Id */
      quranpedia_ayah_id: number;
      /**
       * Version
       * @description `dump:<dump version>` or `change:<time of the correction>`
       */
      version: string;
      /** Dump Version */
      dump_version: string | null;
      /** Last Sync At */
      last_sync_at: string | null;
    };
    /** QuranVerseOut */
    QuranVerseOut: {
      /** Surah */
      surah: number;
      /** Ayah */
      ayah: number;
      /** Surah Name */
      surah_name: string;
      /**
       * Text
       * @description Exactly as stored; never normalised
       */
      text: string;
      /**
       * Sha256
       * @description SHA-256 of the UTF-8 bytes of `text`
       */
      sha256: string;
      /** Page */
      page: number;
      /** Juz */
      juz: number;
      source: components['schemas']['QuranSource'];
      links: components['schemas']['QuranLinks'];
      /**
       * Status
       * @default local_corpus
       * @constant
       */
      status: 'local_corpus';
    };
    /** Readiness */
    Readiness: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded';
      /** Checks */
      checks: {
        [key: string]: 'ok' | 'down';
      };
    };
    /**
     * ReligiousBackground
     * @enum {string}
     */
    ReligiousBackground: 'muslim' | 'non_muslim' | 'unknown';
    /** ResetPasswordIn */
    ResetPasswordIn: {
      /** Token */
      token: string;
      /** Password */
      password: string;
    };
    /**
     * ReverseResult
     * @description What is near a point. Every field is null when no populated place is in range.
     */
    ReverseResult: {
      place: components['schemas']['NearbyPlace'] | null;
      admin_area: components['schemas']['AdminArea'] | null;
      country: components['schemas']['CountryRef'] | null;
    };
    /** RulingOut */
    RulingOut: {
      /**
       * Ruling Text
       * @description As dorar.net gives it, copied by an editor
       */
      ruling_text: string;
      /** Scholar */
      scholar: string;
      /** Source Book */
      source_book: string;
      /** Page */
      page: string;
      /** Dorar Url */
      dorar_url: string;
      classification: components['schemas']['HadithClassification'];
      /**
       * Recorded At
       * Format: date-time
       */
      recorded_at: string;
    };
    /**
     * Section
     * @description A kind of public page. The names are part of the web app's URLs for the child sitemaps.
     * @enum {string}
     */
    Section: 'static' | 'insights' | 'posts' | 'places' | 'profiles';
    /**
     * SessionExport
     * @description A session without its token hash, which is a credential.
     */
    SessionExport: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /**
       * Last Seen At
       * Format: date-time
       */
      last_seen_at: string;
      /** Ip Hash */
      ip_hash: string | null;
      /** User Agent */
      user_agent: string | null;
    };
    /** SignupIn */
    SignupIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Display Name */
      display_name: string;
    };
    /**
     * SitemapEntry
     * @description One URL: a path of the web app (the web app adds the origin), its change date, its pictures.
     */
    SitemapEntry: {
      /** Path */
      path: string;
      /** Lastmod */
      lastmod?: string | null;
      /** Images */
      images?: string[];
    };
    /**
     * SitemapIndex
     * @description The sitemap index: how every advertised section is cut into pages.
     *
     *     A section whose feature is off is missing; a section with nothing to list has no pages.
     */
    SitemapIndex: {
      /** Page Size */
      page_size: number;
      /** Sections */
      sections: {
        [key: string]: components['schemas']['SitemapPage'][];
      };
    };
    /**
     * SitemapPage
     * @description One page of a section: its number from 0, and the newest `lastmod` it holds.
     */
    SitemapPage: {
      /** Page */
      page: number;
      /** Lastmod */
      lastmod?: string | null;
    };
    /** SpanOut */
    SpanOut: {
      /** Start */
      start: number;
      /** End */
      end: number;
      role: components['schemas']['SpanRole'];
    };
    /**
     * SpanRole
     * @enum {string}
     */
    SpanRole: 'chain' | 'body' | 'words' | 'tail';
    /**
     * StatusOut
     * @description The answer of the routes that report only that they did what was asked.
     */
    StatusOut: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'accepted';
    };
    /**
     * Theme
     * @enum {string}
     */
    Theme: 'system' | 'light' | 'dark';
    /** UserExport */
    UserExport: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
      /** Is Admin */
      is_admin: boolean;
      /** Is Active */
      is_active: boolean;
      /** Email Verified At */
      email_verified_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * UserOut
     * @description The signed-in user's own account. Nothing of the private profile is here.
     */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
      /** Is Admin */
      is_admin: boolean;
      /** Email Verified */
      email_verified: boolean;
      /** Has Password */
      has_password: boolean;
      /** Providers */
      providers: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** VerifyEmailIn */
    VerifyEmailIn: {
      /** Token */
      token: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Liveness'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  readiness_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Readiness'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Readiness'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  signup_auth_signup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  me_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  providers_auth_providers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProvidersOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  verify_email_auth_verify_email_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmailIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  resend_verification_auth_resend_verification_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  forgot_password_auth_forgot_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  reset_password_auth_reset_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  start_auth_google_start_get: {
    parameters: {
      query?: {
        /** @description A path in the web app to return to; anything else is ignored. */
        next?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  callback_auth_google_callback_get: {
    parameters: {
      query?: {
        code?: string | null;
        state?: string | null;
        error?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_profile_profile_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfileOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  patch_profile_profile_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfilePatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfileOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  post_consent_consents_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsentIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsentOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  export_account_account_export_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountExport'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  delete_account_account_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  search_geo_search_get: {
    parameters: {
      query: {
        /** @description Part of a place name */
        q: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlaceHit'][];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  reverse_geo_reverse_get: {
    parameters: {
      query: {
        /** @description Degrees, -90 to 90; 0 is valid */
        lat: number;
        /** @description Degrees, -180 to 180; 0 is valid */
        lng: number;
        /** @description Search radius in metres */
        radius_m?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReverseResult'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  countries_geo_countries_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Country'][];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  quran_verse_scripture_quran__surah___ayah__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        surah: number;
        ayah: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuranVerseOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  hadith_scripture_hadith__collection___number__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collection: string;
        number: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HadithOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  report_client_errors_client_errors_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ClientReportBatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_policy_consent_policy_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsentPolicyOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  post_consent_consent_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CookieConsentIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CookieConsentOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_consent_consent__consent_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consent_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CookieConsentOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  sitemap_index_sitemap_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SitemapIndex'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  sitemap_section_sitemap__section__get: {
    parameters: {
      query?: {
        page?: number;
      };
      header?: never;
      path: {
        section: components['schemas']['Section'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SitemapEntry'][];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
