/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness
     * @description Report that the process is up and serving.
     *
     *     Touches no dependency, so it stays cheap enough for a per-second probe and
     *     answers even when the database is down.
     */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness
     * @description Report whether this process can serve a request, which needs the database.
     *
     *     The check is bounded by the connect timeout, so a database that is down or
     *     hangs answers 503 `degraded` quickly instead of holding the request.
     */
    get: operations['readiness_health_ready_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create an account with an e-mail address and a password
     * @description Create the account, sign it in, and mail a verification link.
     *
     *     The new account can be used at once; its address stays unverified until the
     *     link is followed. Rate limited per IP and per e-mail address. A mail that
     *     cannot be sent never fails the sign-up.
     */
    post: operations['signup_auth_signup_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign in with an e-mail address and a password
     * @description Start a session.
     *
     *     A wrong address and a wrong password answer the same 401. Rate limited per IP
     *     and per e-mail address, counting failed attempts, before the password is checked.
     */
    post: operations['login_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * End the current session
     * @description End the session and clear the cookie. Safe to repeat, and to call with no session.
     */
    post: operations['logout_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The signed-in account
     * @description Return the caller's own account. The private profile fields are not part of it.
     */
    get: operations['me_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Which ways of signing in are available
     * @description Whether password and Google sign-in can be used, for the sign-in page to show.
     */
    get: operations['providers_auth_providers_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm an e-mail address with the mailed link's token
     * @description Mark the address verified. The token works once; any bad token answers the same 400.
     *
     *     The caller needs no session: whoever holds the token read the mail.
     */
    post: operations['verify_email_auth_verify_email_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/resend-verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mail the verification link again
     * @description Answer 202 whether or not the address has an unverified account.
     *
     *     Rate limited per IP and per address. A new link cancels the earlier one.
     */
    post: operations['resend_verification_auth_resend_verification_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/forgot-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mail a password reset link
     * @description Answer 202 whether or not the address has an account.
     *
     *     Rate limited per IP and per address. A new link cancels the earlier one. The
     *     mail is sent after the answer, so the time it takes says nothing either.
     */
    post: operations['forgot_password_auth_forgot_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Choose a new password with the mailed link's token
     * @description Set the new password and end every other session of the account.
     *
     *     The token works once. Following it also proves the address, so it is marked
     *     verified. The caller is not signed in by it: they sign in with the new password.
     */
    post: operations['reset_password_auth_reset_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/google/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Send the browser to Google to sign in
     * @description Begin the authorization code flow with PKCE (S256), a state and a nonce.
     *
     *     Redirects to Google. The state, the code verifier and the nonce are kept on
     *     the server for GOOGLE_STATE_TTL_SECONDS; a cookie ties them to this browser.
     */
    get: operations['start_auth_google_start_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/google/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Where Google sends the browser back
     * @description Finish the sign-in: check the state, exchange the code, validate the ID token.
     *
     *     Then link or create the account, start a session and redirect to the web app.
     */
    get: operations['callback_auth_google_callback_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The caller's profile
     * @description Return the caller's own profile, empty answers as `unknown`.
     *
     *     The religious background, the gender and the age range are private: this
     *     route and the account export are the only places they are ever returned.
     */
    get: operations['get_profile_profile_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Change some answers of the caller's profile
     * @description Change the fields sent and no others.
     *
     *     Enums are validated; a null is refused (send `unknown` to clear an answer).
     *     The three consent switches change through `POST /consents` only.
     */
    patch: operations['patch_profile_profile_patch'];
    trace?: never;
  };
  '/consents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record an answer to a consent question
     * @description Append the answer to the user's consent history, and update the matching switch.
     *
     *     A consent is withdrawn by recording the same kind with `granted` false. The
     *     history is never edited.
     */
    post: operations['post_consent_consents_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/account/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download everything the account owns
     * @description Return the account, its profile, consents, linked identities and sessions as JSON.
     */
    get: operations['export_account_account_export_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/account': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete the account and everything it owns
     * @description Delete the user, their profile, consents, linked identities and every session.
     *
     *     Idempotent: without a valid session there is nothing left to delete, and the
     *     answer is the same 204 that clears the cookie.
     */
    delete: operations['delete_account_account_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AccountExport
     * @description Everything the account owns so far, for its owner.
     *
     *     A table that gets a user id later must be added here and to the deletion in
     *     `account_service`; a test fails when a table references `users` without a cascade.
     */
    AccountExport: {
      /**
       * Exported At
       * Format: date-time
       */
      exported_at: string;
      user: components['schemas']['UserExport'];
      /** Oauth Accounts */
      oauth_accounts: components['schemas']['OAuthAccountExport'][];
      /** Sessions */
      sessions: components['schemas']['SessionExport'][];
      profile: components['schemas']['ProfileOut'];
      /** Consents */
      consents: components['schemas']['ConsentOut'][];
    };
    /**
     * AgeRange
     * @enum {string}
     */
    AgeRange: 'under_13' | '13_17' | '18_24' | '25_39' | '40_59' | '60_plus' | 'unknown';
    /** ConsentIn */
    ConsentIn: {
      kind: components['schemas']['ConsentKind'];
      /** Version */
      version: string;
      /** Granted */
      granted: boolean;
    };
    /**
     * ConsentKind
     * @enum {string}
     */
    ConsentKind: 'terms' | 'photo_storage' | 'personalization' | 'memory';
    /** ConsentOut */
    ConsentOut: {
      kind: components['schemas']['ConsentKind'];
      /** Version */
      version: string;
      /** Granted */
      granted: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * EmailIn
     * @description An address, for the routes that mail a link to it.
     */
    EmailIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /**
     * ErrorCode
     * @description The stable error codes. A code is never renamed or reused.
     * @enum {string}
     */
    ErrorCode:
      | 'BAD_REQUEST'
      | 'UNAUTHORIZED'
      | 'FORBIDDEN'
      | 'NOT_FOUND'
      | 'METHOD_NOT_ALLOWED'
      | 'CONFLICT'
      | 'VALIDATION_ERROR'
      | 'RATE_LIMITED'
      | 'INTERNAL_ERROR'
      | 'SERVICE_UNAVAILABLE'
      | 'HTTP_ERROR'
      | 'INVALID_CREDENTIALS'
      | 'EMAIL_TAKEN'
      | 'ACCOUNT_DISABLED'
      | 'EMAIL_NOT_VERIFIED'
      | 'INVALID_TOKEN'
      | 'ORIGIN_NOT_ALLOWED'
      | 'CONSENT_NOT_ALLOWED'
      | 'GOOGLE_NOT_CONFIGURED';
    /**
     * ErrorResponse
     * @description The body of every error response.
     */
    ErrorResponse: {
      error: components['schemas']['ErrorCode'];
      /** Detail */
      detail: string;
      /** Fields */
      fields?: components['schemas']['FieldError'][] | null;
    };
    /**
     * FieldError
     * @description One rejected field of a request: where it is and why it was refused.
     */
    FieldError: {
      /** Loc */
      loc: (string | number)[];
      /** Message */
      message: string;
      /** Type */
      type: string;
    };
    /**
     * Gender
     * @enum {string}
     */
    Gender: 'man' | 'woman' | 'unknown';
    /**
     * Goal
     * @description Why the user is here (master prompt v2, section 5); several may be chosen.
     * @enum {string}
     */
    Goal:
      | 'discover_islam'
      | 'reflection'
      | 'learn_quran_sunnah'
      | 'live_values'
      | 'research'
      | 'teaching'
      | 'curiosity';
    /**
     * KnowledgeLevel
     * @enum {string}
     */
    KnowledgeLevel: 'new' | 'general' | 'advanced' | 'specialist' | 'unknown';
    /** Liveness */
    Liveness: {
      /**
       * Status
       * @constant
       */
      status: 'ok';
    };
    /** LoginIn */
    LoginIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** OAuthAccountExport */
    OAuthAccountExport: {
      /** Provider */
      provider: string;
      /** Subject */
      subject: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ProfileOut */
    ProfileOut: {
      /** Goals */
      goals: components['schemas']['Goal'][];
      knowledge_level: components['schemas']['KnowledgeLevel'];
      age_range: components['schemas']['AgeRange'];
      religious_background: components['schemas']['ReligiousBackground'];
      gender: components['schemas']['Gender'];
      /** Language */
      language: string;
      /** Personalization Enabled */
      personalization_enabled: boolean;
      /** Memory Enabled */
      memory_enabled: boolean;
      /** Photo Storage Consent */
      photo_storage_consent: boolean;
      theme: components['schemas']['Theme'];
      /** Sound Enabled */
      sound_enabled: boolean;
      /** Consent Version */
      consent_version: string | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ProfilePatch
     * @description The fields a user may change, any of them, alone.
     *
     *     The three consent switches are not here: they change only through
     *     `POST /consents`, which records the answer. A field sent as null is refused;
     *     to clear an answer, send `unknown` (or `[]` for the goals).
     */
    ProfilePatch: {
      /** Goals */
      goals?: components['schemas']['Goal'][] | null;
      knowledge_level?: components['schemas']['KnowledgeLevel'] | null;
      age_range?: components['schemas']['AgeRange'] | null;
      religious_background?: components['schemas']['ReligiousBackground'] | null;
      gender?: components['schemas']['Gender'] | null;
      /** Language */
      language?: string | null;
      theme?: components['schemas']['Theme'] | null;
      /** Sound Enabled */
      sound_enabled?: boolean | null;
    };
    /** ProviderOut */
    ProviderOut: {
      /**
       * Id
       * @enum {string}
       */
      id: 'password' | 'google';
      /** Available */
      available: boolean;
    };
    /** ProvidersOut */
    ProvidersOut: {
      /** Providers */
      providers: components['schemas']['ProviderOut'][];
    };
    /** Readiness */
    Readiness: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded';
      /** Checks */
      checks: {
        [key: string]: 'ok' | 'down';
      };
    };
    /**
     * ReligiousBackground
     * @enum {string}
     */
    ReligiousBackground: 'muslim' | 'non_muslim' | 'unknown';
    /** ResetPasswordIn */
    ResetPasswordIn: {
      /** Token */
      token: string;
      /** Password */
      password: string;
    };
    /**
     * SessionExport
     * @description A session without its token hash, which is a credential.
     */
    SessionExport: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /**
       * Last Seen At
       * Format: date-time
       */
      last_seen_at: string;
      /** Ip Hash */
      ip_hash: string | null;
      /** User Agent */
      user_agent: string | null;
    };
    /** SignupIn */
    SignupIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Display Name */
      display_name: string;
    };
    /**
     * StatusOut
     * @description The answer of the routes that report only that they did what was asked.
     */
    StatusOut: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'accepted';
    };
    /**
     * Theme
     * @enum {string}
     */
    Theme: 'system' | 'light' | 'dark';
    /** UserExport */
    UserExport: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
      /** Is Admin */
      is_admin: boolean;
      /** Is Active */
      is_active: boolean;
      /** Email Verified At */
      email_verified_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * UserOut
     * @description The signed-in user's own account. Nothing of the private profile is here.
     */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
      /** Is Admin */
      is_admin: boolean;
      /** Email Verified */
      email_verified: boolean;
      /** Has Password */
      has_password: boolean;
      /** Providers */
      providers: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** VerifyEmailIn */
    VerifyEmailIn: {
      /** Token */
      token: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Liveness'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  readiness_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Readiness'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Readiness'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  signup_auth_signup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  me_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  providers_auth_providers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProvidersOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  verify_email_auth_verify_email_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmailIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  resend_verification_auth_resend_verification_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  forgot_password_auth_forgot_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  reset_password_auth_reset_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatusOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  start_auth_google_start_get: {
    parameters: {
      query?: {
        /** @description A path in the web app to return to; anything else is ignored. */
        next?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  callback_auth_google_callback_get: {
    parameters: {
      query?: {
        code?: string | null;
        state?: string | null;
        error?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_profile_profile_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfileOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  patch_profile_profile_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfilePatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfileOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  post_consent_consents_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsentIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsentOut'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  export_account_account_export_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountExport'];
        };
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  delete_account_account_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description An error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
