"""
Vocabularies of the detector: the default open vocabulary, COCO, and Arabic labels.

The default labels are everyday and concrete, the things a person is likely to
photograph and then want to relate to a verse and a hadith: food, family, nature,
animals, trade, tools, the home, the road, the weather. They are English because
the text encoders (CLIP, MobileCLIP) understand English; the Arabic label is
attached to what the detector returns.

A label that has no entry in `ARABIC_LABELS` (a vocabulary sent by a caller) gets
no Arabic label. The service never guesses a translation.
"""

from __future__ import annotations

from collections.abc import Iterable

DEFAULT_VOCABULARY: tuple[str, ...] = (
    # people
    "person",
    "child",
    # devices and media
    "smartphone",
    "laptop",
    "tv",
    "book",
    "quran",
    "notebook",
    "pen",
    # tableware and food
    "cup",
    "coffee cup",
    "plate",
    "bread",
    "food",
    "fruit",
    "dates",
    "water bottle",
    "tea",
    "milk",
    "honey",
    "olive",
    "rice",
    "meat",
    "apple",
    "orange",
    "banana",
    # furniture and the home
    "table",
    "chair",
    "bed",
    "door",
    "window",
    "lamp",
    "house",
    "building",
    "kitchen",
    "mirror",
    "soap",
    "towel",
    "candle",
    "trash can",
    "garbage",
    "medicine",
    "wheelchair",
    # nature and weather
    "tree",
    "palm tree",
    "plant",
    "flower",
    "grass",
    "leaf",
    "rain",
    "cloud",
    "sky",
    "sun",
    "moon",
    "stars",
    "mountain",
    "river",
    "sea",
    "sand",
    "rock",
    "garden",
    "field",
    "farm",
    "forest",
    "desert",
    "beach",
    "wave",
    "snow",
    "lightning",
    "rainbow",
    "fire",
    "smoke",
    "well",
    "tent",
    # animals
    "cat",
    "dog",
    "bird",
    "sheep",
    "goat",
    "camel",
    "horse",
    "chicken",
    "fish",
    "bee",
    "ant",
    # transport and infrastructure
    "car",
    "bus",
    "bicycle",
    "motorcycle",
    "boat",
    "airplane",
    "road",
    "bridge",
    # worship and trade
    "mosque",
    "prayer rug",
    "market stall",
    "scale",
    "money",
    "coin",
    "wallet",
    "bag",
    # clothing and personal items
    "shoes",
    "clothes",
    "hat",
    "glasses",
    "watch",
    "clock",
    "key",
    "umbrella",
    # tools and play
    "knife",
    "hammer",
    "tool",
    "ball",
    "toy",
)

# The 80 classes a YOLO-World checkpoint knows without a text encoder.
COCO_CLASSES: tuple[str, ...] = (
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)

ARABIC_LABELS: dict[str, str] = {
    # people
    "person": "شخص",
    "child": "طفل",
    # devices and media
    "smartphone": "هاتف ذكي",
    "cell phone": "هاتف محمول",
    "laptop": "حاسوب محمول",
    "tv": "تلفاز",
    "book": "كتاب",
    "quran": "مصحف",
    "notebook": "دفتر",
    "pen": "قلم",
    "mouse": "فأرة حاسوب",
    "keyboard": "لوحة مفاتيح",
    "remote": "جهاز تحكم عن بعد",
    # tableware and food
    "cup": "كوب",
    "coffee cup": "فنجان قهوة",
    "plate": "صحن",
    "bowl": "وعاء",
    "fork": "شوكة",
    "spoon": "ملعقة",
    "bottle": "زجاجة",
    "wine glass": "كأس نبيذ",
    "bread": "خبز",
    "food": "طعام",
    "fruit": "فاكهة",
    "dates": "تمر",
    "water bottle": "زجاجة ماء",
    "tea": "شاي",
    "milk": "حليب",
    "honey": "عسل",
    "olive": "زيتون",
    "rice": "أرز",
    "meat": "لحم",
    "apple": "تفاح",
    "orange": "برتقال",
    "banana": "موز",
    "sandwich": "شطيرة",
    "broccoli": "بروكلي",
    "carrot": "جزر",
    "hot dog": "هوت دوغ",
    "pizza": "بيتزا",
    "donut": "دونات",
    "cake": "كعكة",
    # furniture and the home
    "table": "طاولة",
    "dining table": "طاولة طعام",
    "chair": "كرسي",
    "couch": "أريكة",
    "bench": "مقعد",
    "bed": "سرير",
    "door": "باب",
    "window": "نافذة",
    "lamp": "مصباح",
    "house": "بيت",
    "building": "مبنى",
    "kitchen": "مطبخ",
    "mirror": "مرآة",
    "soap": "صابون",
    "towel": "منشفة",
    "candle": "شمعة",
    "trash can": "سلة مهملات",
    "garbage": "قمامة",
    "medicine": "دواء",
    "wheelchair": "كرسي متحرك",
    "toilet": "مرحاض",
    "sink": "حوض",
    "refrigerator": "ثلاجة",
    "microwave": "ميكروويف",
    "oven": "فرن",
    "toaster": "محمصة خبز",
    "vase": "مزهرية",
    "scissors": "مقص",
    "toothbrush": "فرشاة أسنان",
    "hair drier": "مجفف شعر",
    # nature and weather
    "tree": "شجرة",
    "palm tree": "نخلة",
    "plant": "نبتة",
    "potted plant": "نبتة في أصيص",
    "flower": "زهرة",
    "grass": "عشب",
    "leaf": "ورقة شجر",
    "rain": "مطر",
    "cloud": "سحابة",
    "sky": "سماء",
    "sun": "شمس",
    "moon": "قمر",
    "stars": "نجوم",
    "mountain": "جبل",
    "river": "نهر",
    "sea": "بحر",
    "sand": "رمل",
    "rock": "صخرة",
    "garden": "حديقة",
    "field": "حقل",
    "farm": "مزرعة",
    "forest": "غابة",
    "desert": "صحراء",
    "beach": "شاطئ",
    "wave": "موجة",
    "snow": "ثلج",
    "lightning": "برق",
    "rainbow": "قوس قزح",
    "fire": "نار",
    "smoke": "دخان",
    "well": "بئر",
    "tent": "خيمة",
    # animals
    "cat": "قطة",
    "dog": "كلب",
    "bird": "طائر",
    "sheep": "خروف",
    "goat": "ماعز",
    "camel": "جمل",
    "horse": "حصان",
    "chicken": "دجاجة",
    "fish": "سمكة",
    "bee": "نحلة",
    "ant": "نملة",
    "cow": "بقرة",
    "elephant": "فيل",
    "bear": "دب",
    "zebra": "حمار وحشي",
    "giraffe": "زرافة",
    "teddy bear": "دبدوب",
    # transport and infrastructure
    "car": "سيارة",
    "bus": "حافلة",
    "bicycle": "دراجة هوائية",
    "motorcycle": "دراجة نارية",
    "boat": "قارب",
    "airplane": "طائرة",
    "train": "قطار",
    "truck": "شاحنة",
    "road": "طريق",
    "bridge": "جسر",
    "traffic light": "إشارة مرور",
    "fire hydrant": "صنبور إطفاء",
    "stop sign": "لافتة قف",
    "parking meter": "عداد موقف",
    # worship and trade
    "mosque": "مسجد",
    "prayer rug": "سجادة صلاة",
    "market stall": "كشك في السوق",
    "scale": "ميزان",
    "money": "مال",
    "coin": "عملة معدنية",
    "wallet": "محفظة",
    "bag": "حقيبة",
    "backpack": "حقيبة ظهر",
    "handbag": "حقيبة يد",
    "suitcase": "حقيبة سفر",
    # clothing and personal items
    "shoes": "حذاء",
    "clothes": "ملابس",
    "hat": "قبعة",
    "glasses": "نظارة",
    "watch": "ساعة يد",
    "clock": "ساعة",
    "key": "مفتاح",
    "umbrella": "مظلة",
    "tie": "ربطة عنق",
    # tools and play
    "knife": "سكين",
    "hammer": "مطرقة",
    "tool": "أداة",
    "ball": "كرة",
    "toy": "لعبة",
    "sports ball": "كرة رياضية",
    "frisbee": "قرص طائر",
    "kite": "طائرة ورقية",
    "skis": "زلاجات",
    "snowboard": "لوح تزلج على الثلج",
    "skateboard": "لوح تزلج",
    "surfboard": "لوح ركوب الأمواج",
    "baseball bat": "مضرب بيسبول",
    "baseball glove": "قفاز بيسبول",
    "tennis racket": "مضرب تنس",
}


def arabic_label(label: str) -> str | None:
    """Return the Arabic label of an English one, or None when none is known."""
    return ARABIC_LABELS.get(label)


def normalise_vocabulary(raw: str | Iterable[str] | None) -> list[str]:
    """
    Turn a comma-separated string or a list into a clean, de-duplicated label list.

    Labels are lower-cased and their whitespace is collapsed, so equal vocabularies
    compare equal and the detector can keep the encoded one. Without a usable label
    the default vocabulary is returned.
    """
    if raw is None:
        items: list[str] = []
    elif isinstance(raw, str):
        items = raw.split(",")
    else:
        items = [part for entry in raw for part in entry.split(",")]

    labels = list(dict.fromkeys(" ".join(item.lower().split()) for item in items))
    labels = [label for label in labels if label]
    return labels or list(DEFAULT_VOCABULARY)
