#!/usr/bin/env bash
# Install the tracked host configuration of the application host: the nginx
# site and snippets, the systemd units and timers, the log rotation. Run as
# root, by an administrator, from the release you want to apply; deploy.sh never
# does this (the deploy user has no right to write /etc), it only warns when
# the host differs from the checkout.
#
# nginx: every file is built aside, the current ones are kept, `nginx -t` runs
# on the new set, and when it fails the previous files are put back and nginx is
# not reloaded. nginx only reloads (gracefully) a set that passed.
#
# Generated here, because they depend on the host and never live in git:
#   tabsira-tls.conf          certbot's certificate of tabsira.me, www and api
#   tabsira-admin-tls.conf    the certificate of admin.tabsira.me (DNS challenge)
#   tabsira-admin-listen.conf listen on APP_HOST_VPN_IP only, allow VPN_SUBNET, deny all
#
# Usage:
#   sudo deploy/apply-config.sh [--check | --dry-run]
#   --check     exit 1 and list what differs; change nothing (no root needed
#               for the comparison of the files it can read)
#   --dry-run   print the plan
#
# Environment: APP_USER (tabsira), APP_GROUP (its group), APP_ROOT
# (/srv/tabsira), APP_HOME (the user's home), APP_HOST_VPN_IP (required),
# VPN_SUBNET (100.64.0.0/10, Netbird's default), TLS_NAME (tabsira.me),
# ADMIN_TLS_NAME (admin.tabsira.me), LE_DIR (/etc/letsencrypt/live).

set -Eeuo pipefail
# shellcheck disable=SC1091
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/lib.sh"
# shellcheck disable=SC1091
source "$DEPLOY_DIR/net-lib.sh"

MODE="apply"
case "${1:-}" in
--check) MODE="check" ;;
--dry-run)
	MODE="dry"
	set_dry_run
	;;
"") ;;
*) die "usage: apply-config.sh [--check | --dry-run]" ;;
esac

APP_USER="${APP_USER:-tabsira}"
APP_GROUP="${APP_GROUP:-$(id -gn "$APP_USER" 2>/dev/null || echo "$APP_USER")}"
APP_HOME="${APP_HOME:-$(getent passwd "$APP_USER" 2>/dev/null | cut -d: -f6 || true)}"
APP_HOME="${APP_HOME:-/home/$APP_USER}"
VPN_SUBNET="${VPN_SUBNET:-100.64.0.0/10}"
TLS_NAME="${TLS_NAME:-tabsira.me}"
ADMIN_TLS_NAME="${ADMIN_TLS_NAME:-admin.tabsira.me}"
LE_DIR="${LE_DIR:-/etc/letsencrypt/live}"
require_app_host
[[ "$VPN_SUBNET" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[12][0-9]|3[0-2])$ ]] || die "VPN_SUBNET must be an IPv4 CIDR."
[[ "${VPN_SUBNET##*/}" -ge 8 ]] || die "Refusing VPN_SUBNET=$VPN_SUBNET: name the VPN's network, not the internet."

NGINX_SRC="$REPO_ROOT/nginx/production"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

# staged file, installed path, mode
FILES=()
add() { FILES+=("$1|$2"); }

# fill NAME DEST: substitute the placeholders of a tracked template.
fill() {
	sed -e "s#@APP_USER@#$APP_USER#g" -e "s#@APP_GROUP@#$APP_GROUP#g" \
		-e "s#@APP_ROOT@#$APP_ROOT#g" -e "s#@APP_HOME@#$APP_HOME#g" "$1" >"$2"
}

# ─── Build every file aside ─────────────────────────────────────────
cp "$NGINX_SRC/tabsira.me.conf" "$STAGE/site"
add "$STAGE/site" /etc/nginx/sites-available/tabsira
for snippet in "$NGINX_SRC"/snippets/*.conf; do
	cp "$snippet" "$STAGE/$(basename "$snippet")"
	add "$STAGE/$(basename "$snippet")" "/etc/nginx/snippets/$(basename "$snippet")"
done
cat >"$STAGE/tabsira-tls.conf" <<EOF
# Generated by deploy/apply-config.sh. certbot renews these files in place.
ssl_certificate     $LE_DIR/$TLS_NAME/fullchain.pem;
ssl_certificate_key $LE_DIR/$TLS_NAME/privkey.pem;
EOF
add "$STAGE/tabsira-tls.conf" /etc/nginx/snippets/tabsira-tls.conf
cat >"$STAGE/tabsira-admin-tls.conf" <<EOF
# Generated by deploy/apply-config.sh. The admin host has its own certificate,
# issued by a DNS challenge: the host is not reachable from the internet.
ssl_certificate     $LE_DIR/$ADMIN_TLS_NAME/fullchain.pem;
ssl_certificate_key $LE_DIR/$ADMIN_TLS_NAME/privkey.pem;
EOF
add "$STAGE/tabsira-admin-tls.conf" /etc/nginx/snippets/tabsira-admin-tls.conf
cat >"$STAGE/tabsira-admin-listen.conf" <<EOF
# Generated by deploy/apply-config.sh. The admin host listens on this host's
# VPN address only; the allow/deny pair is a second guard.
listen $APP_HOST_VPN_IP:443 ssl http2;
allow $VPN_SUBNET;
deny  all;
EOF
add "$STAGE/tabsira-admin-listen.conf" /etc/nginx/snippets/tabsira-admin-listen.conf

for unit in "$DEPLOY_DIR"/systemd/*; do
	fill "$unit" "$STAGE/$(basename "$unit")"
	add "$STAGE/$(basename "$unit")" "/etc/systemd/system/$(basename "$unit")"
done
fill "$DEPLOY_DIR/logrotate/tabsira" "$STAGE/logrotate"
add "$STAGE/logrotate" /etc/logrotate.d/tabsira

# ─── Compare ────────────────────────────────────────────────────────
changed=()
for entry in "${FILES[@]}"; do
	cmp -s "${entry%%|*}" "${entry##*|}" 2>/dev/null || changed+=("${entry##*|}")
done

if [[ "$MODE" == "check" ]]; then
	if ((${#changed[@]} == 0)); then
		ok "The host matches this checkout."
		exit 0
	fi
	warn "The host differs from this checkout: ${changed[*]}"
	warn "Apply it: sudo $DEPLOY_DIR/apply-config.sh"
	exit 1
fi
if [[ "$MODE" == "dry" ]]; then
	log "Would install ${#FILES[@]} file(s); ${#changed[@]} differ:"
	for path in "${changed[@]}"; do log "  $path"; done
	log "Then: nginx -t (restoring the previous files if it fails), systemctl daemon-reload, enable the timers, reload nginx."
	log "admin listens on $APP_HOST_VPN_IP:443, allow $VPN_SUBNET, certificate $LE_DIR/$ADMIN_TLS_NAME/"
	ok "Dry run complete: nothing was changed."
	exit 0
fi

[[ $EUID -eq 0 ]] || die "Run as root (sudo)."
for cert in "$TLS_NAME" "$ADMIN_TLS_NAME"; do
	[[ -s "$LE_DIR/$cert/fullchain.pem" ]] ||
		die "No certificate at $LE_DIR/$cert. Issue it first (deploy/provision-app.sh explains how); nginx would refuse to start without it."
done

# ─── Install, test, restore on failure ──────────────────────────────
BACKUP="$STAGE/backup"
mkdir -p "$BACKUP"
n=0
for entry in "${FILES[@]}"; do
	n=$((n + 1))
	[[ -f "${entry##*|}" ]] && cp -p "${entry##*|}" "$BACKUP/$n"
done
SITE_LINK=/etc/nginx/sites-enabled/tabsira
DEFAULT_SITE=/etc/nginx/sites-enabled/default
DEFAULT_TARGET="$(readlink "$DEFAULT_SITE" 2>/dev/null || true)"
LINK_WAS=0
[[ -L "$SITE_LINK" ]] && LINK_WAS=1

restore() {
	local i=0 entry
	for entry in "${FILES[@]}"; do
		i=$((i + 1))
		case "${entry##*|}" in /etc/nginx/*) ;; *) continue ;; esac
		if [[ -f "$BACKUP/$i" ]]; then cp -p "$BACKUP/$i" "${entry##*|}"; else rm -f "${entry##*|}"; fi
	done
	((LINK_WAS)) || rm -f "$SITE_LINK"
	[[ -z "$DEFAULT_TARGET" ]] || ln -sfn "$DEFAULT_TARGET" "$DEFAULT_SITE"
}

log "Installing ${#FILES[@]} file(s)"
for entry in "${FILES[@]}"; do
	install -D -m 0644 "${entry%%|*}" "${entry##*|}"
done
ln -sf /etc/nginx/sites-available/tabsira "$SITE_LINK"
# The Debian default site would otherwise answer for any unmatched host.
rm -f "$DEFAULT_SITE"

log "Validating the nginx configuration"
if ! nginx -t; then
	restore
	die "nginx refused the new configuration; the previous files are back and nginx was not reloaded."
fi

systemctl daemon-reload
systemctl enable tabsira-api.service tabsira-vision.service tabsira-worker.service >/dev/null
systemctl enable --now tabsira-sync-quran.timer tabsira-audit-retention.timer >/dev/null
log "Reloading nginx (graceful)"
systemctl reload nginx
ok "Host configuration applied. The API, vision and worker units pick up a changed unit at their next restart."
