"""
What an English detector label means in the ontology's Arabic.

Object detectors (YOLO-World, YOLOE) and vision models name things in English; the
ontology is Arabic. These tables bridge the two for the resolver. They are hints,
not the source of truth: every Arabic term below must be the label of an entity or
one of its related objects (a test holds each one to the real workbook), and the
resolver still scores what it finds like any other query. A label that has no hint
is resolved by its catch-all category, or not at all.

Two rules the tables keep on purpose. A label about a person stays generic: a
detector that says «man», «child» or «doctor» does not make the resolver return a
gender, an age or a role, which the product never infers from a photo. And a hint
points at what the label names, never at what it might be used for.
"""

from __future__ import annotations

# English label (lower case) -> Arabic terms, the most likely first.
VISION_LABEL_HINTS: dict[str, tuple[str, ...]] = {
    "person": ("إنسان", "شخص"),
    "man": ("إنسان",),
    "woman": ("إنسان",),
    "child": ("إنسان",),
    "kid": ("إنسان",),
    "boy": ("إنسان",),
    "girl": ("إنسان",),
    "baby": ("إنسان",),
    "elderly person": ("إنسان",),
    "smartphone": ("هاتف",),
    "mobile phone": ("هاتف",),
    "cell phone": ("هاتف",),
    "phone": ("هاتف",),
    "telephone": ("هاتف",),
    "laptop": ("حاسوب محمول", "حاسوب"),
    "computer": ("حاسوب",),
    "tablet": ("جهاز لوحي", "شاشة"),
    "tv": ("تلفاز",),
    "television": ("تلفاز",),
    "screen": ("شاشة",),
    "monitor": ("شاشة",),
    "keyboard": ("لوحة مفاتيح",),
    "camera": ("كاميرا",),
    "headphones": ("سماعات رأس",),
    "book": ("كتاب",),
    "books": ("كتاب", "مكتبة"),
    "quran": ("مصحف", "مصحف مفتوح"),
    "mushaf": ("مصحف",),
    "notebook": ("دفتر",),
    "pen": ("قلم",),
    "pencil": ("قلم",),
    "newspaper": ("صحيفة",),
    "letter": ("رسالة ورقية",),
    "document": ("وثيقة غير محددة", "وثيقة"),
    "rain": ("مطر",),
    "cloud": ("سحابة",),
    "clouds": ("سحابة",),
    "sky": ("سماء",),
    "sun": ("شمس",),
    "moon": ("قمر",),
    "star": ("نجمة", "نجوم"),
    "stars": ("نجمة",),
    "night sky": ("سماء", "ليل", "نجوم"),
    "night": ("ليل",),
    "lightning": ("برق",),
    "thunder": ("رعد",),
    "wind": ("ريح",),
    "snow": ("ثلج",),
    "fog": ("ضباب",),
    "rainbow": ("قوس قزح",),
    "sunrise": ("شروق",),
    "sunset": ("غروب",),
    "tree": ("شجرة",),
    "trees": ("شجرة",),
    "palm": ("نخلة",),
    "palm tree": ("نخلة",),
    "plant": ("نبات", "نبات غير محدد"),
    "flower": ("زهرة",),
    "flowers": ("زهرة",),
    "grass": ("عشب",),
    "leaf": ("ورقة شجر", "ورق"),
    "seed": ("بذرة",),
    "fruit": ("ثمر",),
    "garden": ("حديقة",),
    "field": ("حقل",),
    "mountain": ("جبل",),
    "hill": ("تل",),
    "desert": ("صحراء",),
    "sand": ("رمل",),
    "rock": ("صخرة", "حجر"),
    "river": ("نهر",),
    "sea": ("بحر",),
    "ocean": ("بحر",),
    "lake": ("بحيرة",),
    "water": ("ماء",),
    "wave": ("موج",),
    "waves": ("موج",),
    "beach": ("شاطئ",),
    "well": ("بئر",),
    "spring": ("عين ماء",),
    "cat": ("قط",),
    "kitten": ("قط",),
    "dog": ("كلب",),
    "bird": ("طائر",),
    "birds": ("طائر",),
    "pigeon": ("حمامة",),
    "sheep": ("خروف", "غنم"),
    "goat": ("ماعز",),
    "cow": ("بقرة",),
    "camel": ("جمل",),
    "horse": ("حصان",),
    "donkey": ("حمار",),
    "chicken": ("دجاجة",),
    "fish": ("سمكة",),
    "bee": ("نحلة",),
    "ant": ("نملة",),
    "butterfly": ("فراشة",),
    "spider": ("عنكبوت",),
    "animal": ("حيوان غير محدد",),
    "insect": ("حشرة",),
    "bread": ("خبز",),
    "food": ("طعام",),
    "meal": ("طعام", "مائدة"),
    "plate": ("صحن تقديم",),
    "dish": ("صحن تقديم", "طعام"),
    "bowl": ("وعاء", "صحن تقديم"),
    "cup": ("كوب",),
    "coffee": ("قهوة", "كوب"),
    "coffee cup": ("كوب", "قهوة"),
    "tea": ("شاي", "كوب"),
    "water bottle": ("ماء",),
    "glass": ("كأس ماء",),
    "wine glass": ("كأس ماء",),
    "apple": ("تفاحة", "تفاح"),
    "orange": ("برتقال",),
    "banana": ("موز",),
    "dates": ("تمرة",),
    "date": ("تمرة",),
    "rice": ("أرز حبوب",),
    "meat": ("لحم",),
    "milk": ("حليب", "لبن"),
    "honey": ("عسل",),
    "olive": ("زيتون",),
    "olive oil": ("زيت زيتون",),
    "dining table": ("مائدة طعام", "مائدة"),
    "table": ("طاولة",),
    "chair": ("كرسي",),
    "bed": ("سرير",),
    "sofa": ("أريكة",),
    "couch": ("أريكة",),
    "lamp": ("مصباح",),
    "light": ("مصباح", "ضوء"),
    "door": ("باب",),
    "window": ("نافذة",),
    "wall": ("جدار",),
    "house": ("منزل", "بيت"),
    "home": ("منزل", "بيت"),
    "building": ("بناء",),
    "kitchen": ("مطبخ",),
    "room": ("غرفة",),
    "mirror": ("مرآة",),
    "clock": ("ساعة حائط",),
    "watch": ("ساعة يد",),
    "key": ("مفتاح",),
    "bag": ("حقيبة",),
    "backpack": ("حقيبة",),
    "wallet": ("محفظة",),
    "money": ("مال",),
    "cash": ("مال",),
    "coin": ("عملة معدنية",),
    "credit card": ("بطاقة دفع",),
    "shop": ("متجر",),
    "store": ("متجر",),
    "market": ("سوق",),
    "bazaar": ("سوق",),
    "scale": ("ميزان بيع", "ميزان"),
    "receipt": ("فاتورة",),
    "car": ("سيارة",),
    "bus": ("حافلة",),
    "truck": ("شاحنة",),
    "bicycle": ("دراجة",),
    "motorcycle": ("دراجة نارية",),
    "train": ("قطار",),
    "airplane": ("طائرة",),
    "plane": ("طائرة",),
    "boat": ("قارب", "سفينة"),
    "ship": ("سفينة",),
    "road": ("طريق",),
    "street": ("شارع", "طريق"),
    "bridge": ("جسر",),
    "traffic light": ("إشارة مرور",),
    "vehicle": ("مركبة غير محددة",),
    "mosque": ("مسجد",),
    "minaret": ("مئذنة",),
    "prayer rug": ("سجادة صلاة",),
    "prayer mat": ("سجادة صلاة",),
    "kaaba": ("الكعبة",),
    "school": ("مدرسة",),
    "classroom": ("فصل دراسي",),
    "hospital": ("مستشفى",),
    "clinic": ("عيادة",),
    "medicine": ("دواء",),
    "pill": ("دواء",),
    "wheelchair": ("كرسي متحرك",),
    "crutch": ("عكاز",),
    "clothes": ("ثوب", "لباس"),
    "shirt": ("قميص",),
    "dress": ("ثوب",),
    "shoes": ("حذاء",),
    "shoe": ("حذاء",),
    "hat": ("قبعة",),
    "scarf": ("وشاح",),
    "glasses": ("نظارة طبية",),
    "soap": ("صابون",),
    "toothbrush": ("سواك", "فرشاة أسنان"),
    "towel": ("منشفة",),
    "hammer": ("مطرقة",),
    "tool": ("أداة غير محددة",),
    "tools": ("أداة غير محددة",),
    "device": ("جهاز غير محدد",),
    "knife": ("سكين مطبخ",),
    "scissors": ("مقص ملابس",),
    "ball": ("لعبة كرة",),
    "football": ("كرة قدم",),
    "smoke": ("دخان كثيف",),
    "garbage": ("نفايات", "قمامة"),
    "trash": ("نفايات",),
    "trash can": ("سلة مهملات",),
    "plastic": ("بلاستيك",),
    "glassware": ("زجاج",),
    "place": ("مكان غير محدد",),
    "object": ("أداة غير محددة",),
    "thing": ("شيء طبيعي غير محدد",),
    "situation": ("موقف غير واضح",),
}

# When a label has no specific entity, a catch-all is offered by what kind of thing it names.
# English words of the label -> the label of the catch-all entity («... غير محدد»).
CATCH_ALL_BY_WORD: dict[str, str] = {
    "plant": "نبات غير محدد",
    "flower": "نبات غير محدد",
    "leaf": "نبات غير محدد",
    "grass": "نبات غير محدد",
    "bush": "نبات غير محدد",
    "vegetation": "نبات غير محدد",
    "animal": "حيوان غير محدد",
    "creature": "حيوان غير محدد",
    "pet": "حيوان غير محدد",
    "bird": "حيوان غير محدد",
    "insect": "حشرة غير محددة",
    "bug": "حشرة غير محددة",
    "food": "طعام غير محدد",
    "meal": "طعام غير محدد",
    "dish": "طعام غير محدد",
    "drink": "شراب غير محدد",
    "beverage": "شراب غير محدد",
    "clothes": "لباس غير محدد",
    "clothing": "لباس غير محدد",
    "garment": "لباس غير محدد",
    "fabric": "لباس غير محدد",
    "tool": "أداة غير محددة",
    "utensil": "أداة غير محددة",
    "instrument": "أداة غير محددة",
    "device": "جهاز غير محدد",
    "gadget": "جهاز غير محدد",
    "machine": "جهاز غير محدد",
    "electronic": "جهاز غير محدد",
    "vehicle": "مركبة غير محددة",
    "transport": "مركبة غير محددة",
    "place": "مكان غير محدد",
    "room": "مكان غير محدد",
    "area": "مكان غير محدد",
    "location": "مكان غير محدد",
    "building": "مكان غير محدد",
    "interior": "مكان غير محدد",
    "landscape": "مكان غير محدد",
    "document": "وثيقة غير محددة",
    "paper": "وثيقة غير محددة",
    "text": "وثيقة غير محددة",
    "page": "وثيقة غير محددة",
    "note": "وثيقة غير محددة",
    "rock": "شيء طبيعي غير محدد",
    "stone": "شيء طبيعي غير محدد",
    "water": "شيء طبيعي غير محدد",
    "natural": "شيء طبيعي غير محدد",
    "nature": "شيء طبيعي غير محدد",
    "cloud": "شيء طبيعي غير محدد",
    "sky": "شيء طبيعي غير محدد",
}

# The same for a label in Arabic that no entity resolved: a word of it -> the catch-all.
CATCH_ALL_BY_ARABIC_WORD: dict[str, str] = {
    "نبات": "نبات غير محدد",
    "نبتة": "نبات غير محدد",
    "شجر": "نبات غير محدد",
    "زهر": "نبات غير محدد",
    "عشب": "نبات غير محدد",
    "حيوان": "حيوان غير محدد",
    "دابة": "حيوان غير محدد",
    "طائر": "حيوان غير محدد",
    "طير": "حيوان غير محدد",
    "حشرة": "حشرة غير محددة",
    "طعام": "طعام غير محدد",
    "أكل": "طعام غير محدد",
    "وجبة": "طعام غير محدد",
    "شراب": "شراب غير محدد",
    "مشروب": "شراب غير محدد",
    "لباس": "لباس غير محدد",
    "ثوب": "لباس غير محدد",
    "ملابس": "لباس غير محدد",
    "أداة": "أداة غير محددة",
    "عدة": "أداة غير محددة",
    "جهاز": "جهاز غير محدد",
    "آلة": "جهاز غير محدد",
    "مركبة": "مركبة غير محددة",
    "وسيلة": "مركبة غير محددة",
    "مكان": "مكان غير محدد",
    "غرفة": "مكان غير محدد",
    "مبنى": "مكان غير محدد",
    "وثيقة": "وثيقة غير محددة",
    "مستند": "وثيقة غير محددة",
    "طبيعة": "شيء طبيعي غير محدد",
}

# The catch-all of last resort: a scene that cannot be told at all.
DEFAULT_CATCH_ALL = "موقف غير واضح"
