"""create_accounts_tables

Revision ID: 20261004_100000
Revises: 20261004_090100
Create Date: 2026-10-04 10:00:00.000000

Accounts, sessions, the optional profile, consent records, the mailed link
tokens and the tables that rate limit sign-in and carry a Google sign-in. Generated by autogenerate, then
edited by hand: the enum columns are text with one named CHECK constraint each
(autogenerate wrote each one twice), and the consents table gets its
append-only trigger, which autogenerate cannot see.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20261004_100000"
down_revision: str | Sequence[str] | None = "20261004_090100"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"


def _created_at() -> sa.Column[sa.DateTime]:
    return sa.Column(
        "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    )


def _uuid_pk() -> sa.Column[sa.Uuid]:
    return sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False)


def upgrade() -> None:
    op.create_table(
        "users",
        _uuid_pk(),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=60), nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        _created_at(),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        schema=SCHEMA,
    )
    # Case-insensitive uniqueness: the addresses are stored lower-cased and this
    # index refuses a second spelling of one address even from a raw insert.
    op.create_index(
        "uq_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
        schema=SCHEMA,
    )

    op.create_table(
        "oauth_accounts",
        _uuid_pk(),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        _created_at(),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"{SCHEMA}.users.id"],
            name=op.f("fk_oauth_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_accounts")),
        sa.UniqueConstraint("provider", "subject", name="uq_oauth_accounts_provider_subject"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_oauth_accounts_user_id", "oauth_accounts", ["user_id"], unique=False, schema=SCHEMA
    )

    op.create_table(
        "sessions",
        _uuid_pk(),
        # SHA-256 of the cookie's random token; the token itself is never stored.
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        _created_at(),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.CheckConstraint(
            "octet_length(token_hash) = 32", name=op.f("ck_sessions_token_hash_length")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"{SCHEMA}.users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
        schema=SCHEMA,
    )
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"], unique=False, schema=SCHEMA)
    op.create_index(
        "ix_sessions_expires_at", "sessions", ["expires_at"], unique=False, schema=SCHEMA
    )

    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "goals",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "knowledge_level", sa.String(length=32), server_default="unknown", nullable=False
        ),
        sa.Column("age_range", sa.String(length=32), server_default="unknown", nullable=False),
        sa.Column(
            "religious_background", sa.String(length=32), server_default="unknown", nullable=False
        ),
        sa.Column("gender", sa.String(length=32), server_default="unknown", nullable=False),
        sa.Column("language", sa.String(length=35), server_default="ar", nullable=False),
        sa.Column(
            "personalization_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("memory_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "photo_storage_consent", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("theme", sa.String(length=32), server_default="system", nullable=False),
        sa.Column("sound_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("consent_version", sa.String(length=32), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "goals <@ ARRAY['discover_islam', 'reflection', 'learn_quran_sunnah', 'live_values', "
            "'research', 'teaching', 'curiosity']::text[]",
            name=op.f("ck_profiles_goals_known"),
        ),
        sa.CheckConstraint(
            "knowledge_level IN ('new', 'general', 'advanced', 'specialist', 'unknown')",
            name=op.f("ck_profiles_knowledge_level"),
        ),
        sa.CheckConstraint(
            "age_range IN ('under_13', '13_17', '18_24', '25_39', '40_59', '60_plus', 'unknown')",
            name=op.f("ck_profiles_age_range"),
        ),
        sa.CheckConstraint(
            "religious_background IN ('muslim', 'non_muslim', 'unknown')",
            name=op.f("ck_profiles_religious_background"),
        ),
        sa.CheckConstraint(
            "gender IN ('man', 'woman', 'unknown')", name=op.f("ck_profiles_gender")
        ),
        sa.CheckConstraint("theme IN ('system', 'light', 'dark')", name=op.f("ck_profiles_theme")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"{SCHEMA}.users.id"],
            name=op.f("fk_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_profiles")),
        schema=SCHEMA,
    )

    op.create_table(
        "consents",
        _uuid_pk(),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        _created_at(),
        sa.CheckConstraint(
            "kind IN ('terms', 'photo_storage', 'personalization', 'memory')",
            name=op.f("ck_consents_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"{SCHEMA}.users.id"],
            name=op.f("fk_consents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_consents_user_id_kind_created_at",
        "consents",
        ["user_id", "kind", "created_at"],
        unique=False,
        schema=SCHEMA,
    )
    # Append-only: a consent is never edited. The row leaves only with its user
    # (ON DELETE CASCADE), which a BEFORE UPDATE trigger does not touch.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION app.consents_forbid_update() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'consents are append-only' USING ERRCODE = 'integrity_constraint_violation';
        END
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER consents_forbid_update BEFORE UPDATE ON app.consents
        FOR EACH ROW EXECUTE FUNCTION app.consents_forbid_update()
        """
    )

    op.create_table(
        "email_tokens",
        _uuid_pk(),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        # SHA-256 of the token in the mailed link; the token itself is never stored.
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        _created_at(),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "purpose IN ('verify_email', 'reset_password')", name=op.f("ck_email_tokens_purpose")
        ),
        sa.CheckConstraint(
            "octet_length(token_hash) = 32", name=op.f("ck_email_tokens_token_hash_length")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"{SCHEMA}.users.id"],
            name=op.f("fk_email_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_email_tokens_token_hash")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_email_tokens_user_id_purpose",
        "email_tokens",
        ["user_id", "purpose"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_index(
        "ix_email_tokens_expires_at", "email_tokens", ["expires_at"], unique=False, schema=SCHEMA
    )

    op.create_table(
        "login_attempts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=False),
        sa.Column("email_hash", sa.String(length=64), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        _created_at(),
        sa.CheckConstraint(
            "kind IN ('login', 'signup', 'google_start', 'resend_verification', "
            "'forgot_password', 'email_token')",
            name=op.f("ck_login_attempts_kind"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_login_attempts_ip_hash_created_at",
        "login_attempts",
        ["ip_hash", "created_at"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_index(
        "ix_login_attempts_email_hash_created_at",
        "login_attempts",
        ["email_hash", "created_at"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_index(
        "ix_login_attempts_created_at",
        "login_attempts",
        ["created_at"],
        unique=False,
        schema=SCHEMA,
    )

    op.create_table(
        "oauth_states",
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("binder_hash", sa.String(length=64), nullable=False),
        sa.Column("code_verifier", sa.String(length=128), nullable=False),
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column("next_path", sa.Text(), nullable=True),
        _created_at(),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("state_hash", name=op.f("pk_oauth_states")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_oauth_states_expires_at", "oauth_states", ["expires_at"], unique=False, schema=SCHEMA
    )


def downgrade() -> None:
    op.drop_table("oauth_states", schema=SCHEMA)
    op.drop_table("login_attempts", schema=SCHEMA)
    op.drop_table("email_tokens", schema=SCHEMA)
    # Dropping the table drops its trigger; the function it called stays until here.
    op.drop_table("consents", schema=SCHEMA)
    op.execute("DROP FUNCTION app.consents_forbid_update()")
    op.drop_table("profiles", schema=SCHEMA)
    op.drop_table("sessions", schema=SCHEMA)
    op.drop_table("oauth_accounts", schema=SCHEMA)
    op.drop_table("users", schema=SCHEMA)
