"""create_ontology_tables

Revision ID: 20261004_110000
Revises: 20261004_100000
Create Date: 2026-10-04 11:00:00.000000

The world ontology and the table of terms it did not know. Generated by
autogenerate, then edited by hand: the unique constraint of the candidates gets
a name that lists both its columns.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20261004_110000"
down_revision: str | Sequence[str] | None = "20261004_100000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "ontology_entities",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("label_ar", sa.Text(), nullable=False),
        sa.Column("related_objects", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("actions_and_uses", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("contextual_concepts", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("special_constraint", sa.Text(), nullable=True),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("is_catch_all", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("label_norm", sa.Text(), nullable=False),
        sa.Column("related_norm", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id ~ '^E[0-9]{3,}$'", name=op.f("ck_ontology_entities_id_format")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ontology_entities")),
        schema="app",
    )
    op.create_index(
        "ix_ontology_entities_domain", "ontology_entities", ["domain"], unique=False, schema="app"
    )
    op.create_index(
        "ix_ontology_entities_label_norm",
        "ontology_entities",
        ["label_norm"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_ontology_entities_related_norm",
        "ontology_entities",
        ["related_norm"],
        unique=False,
        schema="app",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_ontology_entities_search_text_trgm",
        "ontology_entities",
        ["search_text"],
        unique=False,
        schema="app",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.create_table(
        "ontology_candidates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("term", sa.Text(), nullable=False),
        sa.Column("term_norm", sa.Text(), nullable=False),
        sa.Column("count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "sources",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "examples",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), server_default=sa.text("'new'"), nullable=False),
        sa.Column("entity_id", sa.String(length=16), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('label', 'concept')", name=op.f("ck_ontology_candidates_kind")
        ),
        sa.CheckConstraint(
            "status IN ('new', 'accepted', 'rejected')", name=op.f("ck_ontology_candidates_status")
        ),
        sa.CheckConstraint("count >= 1", name=op.f("ck_ontology_candidates_count_positive")),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["app.ontology_entities.id"],
            name=op.f("fk_ontology_candidates_entity_id_ontology_entities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ontology_candidates")),
        sa.UniqueConstraint(
            "kind", "term_norm", name=op.f("uq_ontology_candidates_kind_term_norm")
        ),
        schema="app",
    )
    op.create_index(
        "ix_ontology_candidates_status_count",
        "ontology_candidates",
        ["status", "count"],
        unique=False,
        schema="app",
    )


def downgrade() -> None:
    op.drop_index(
        "ix_ontology_candidates_status_count", table_name="ontology_candidates", schema="app"
    )
    op.drop_table("ontology_candidates", schema="app")
    op.drop_index(
        "ix_ontology_entities_search_text_trgm",
        table_name="ontology_entities",
        schema="app",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_ontology_entities_related_norm",
        table_name="ontology_entities",
        schema="app",
        postgresql_using="gin",
    )
    op.drop_index("ix_ontology_entities_label_norm", table_name="ontology_entities", schema="app")
    op.drop_index("ix_ontology_entities_domain", table_name="ontology_entities", schema="app")
    op.drop_table("ontology_entities", schema="app")
