"""create_scripture_tables

Revision ID: 20261004_121500
Revises: 20261004_120000
Create Date: 2026-10-04 11:00:00.000000

The scripture store: Quran verses of quranpedia mushaf 2 with their history,
the nine hadith books, their search copies, the model-written retrieval
signals, the editors' dorar rulings, the verification queue, the audit log and
the sync state. Generated by autogenerate, then edited by hand: the ruling
classification is text with one named CHECK constraint (autogenerate wrote it
twice), and the write guard and its triggers are added, which autogenerate
cannot see. The guard SQL is the same as in src/models/scripture.py.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20261004_121500"
down_revision: str | Sequence[str] | None = "20261004_120000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

GUARD_FUNCTION = """
CREATE OR REPLACE FUNCTION app.scripture_write_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF coalesce(current_setting('tabsira.scripture_write', true), '') IN ('import', 'sync') THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;
    RAISE EXCEPTION '% on %.% refused: scripture is written only by its importers and the sync job',
        TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME
        USING ERRCODE = 'integrity_constraint_violation';
END
$$
"""

GUARDED_TABLES = {
    "quran_verses": "INSERT OR UPDATE OR DELETE",
    "quran_verse_history": "INSERT OR UPDATE OR DELETE",
    "hadiths": "INSERT OR UPDATE OR DELETE",
    "hadith_rulings": "UPDATE OR DELETE",
    "scripture_audit": "UPDATE OR DELETE",
}


def _create_guards() -> None:
    op.execute(GUARD_FUNCTION)
    for table, events in GUARDED_TABLES.items():
        op.execute(
            f"CREATE TRIGGER {table}_write_guard BEFORE {events} ON app.{table} "
            "FOR EACH ROW EXECUTE FUNCTION app.scripture_write_guard()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_truncate_guard BEFORE TRUNCATE ON app.{table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION app.scripture_write_guard()"
        )


def upgrade() -> None:
    op.create_table(
        "hadith_collections",
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("name_ar", sa.Text(), nullable=False),
        sa.Column("source_dataset", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("licence", sa.Text(), nullable=False),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column("source_file", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_hadith_collections")),
        schema="app",
    )
    op.create_table(
        "quran_surahs",
        sa.Column("number", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("name_ar", sa.Text(), nullable=False),
        sa.Column("revelation_place", sa.Text(), nullable=False),
        sa.Column("revelation_order", sa.SmallInteger(), nullable=False),
        sa.Column("ayah_count", sa.SmallInteger(), nullable=False),
        sa.Column("words_count", sa.Integer(), nullable=False),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("number", name=op.f("pk_quran_surahs")),
        schema="app",
    )
    op.create_table(
        "scripture_audit",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("entity", sa.String(length=32), nullable=False),
        sa.Column("entity_key", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("old_sha256", sa.String(length=64), nullable=True),
        sa.Column("new_sha256", sa.String(length=64), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scripture_audit")),
        schema="app",
    )
    op.create_index(
        "ix_scripture_audit_entity_key",
        "scripture_audit",
        ["entity", "entity_key"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "scripture_sync_state",
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("synced_through", sa.Date(), nullable=False),
        sa.Column("dump_version", sa.Text(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("source", name=op.f("pk_scripture_sync_state")),
        schema="app",
    )
    op.create_table(
        "hadiths",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("collection", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("arabic_number", sa.String(length=32), nullable=True),
        sa.Column("book_number", sa.Integer(), nullable=True),
        sa.Column("book_name", sa.Text(), nullable=True),
        sa.Column("number_in_book", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column("informational_grades", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_dataset", sa.Text(), nullable=False),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("text <> ''", name=op.f("ck_hadiths_text_not_empty")),
        sa.CheckConstraint(
            "text_sha256 = encode(sha256(convert_to(text, 'UTF8')), 'hex')",
            name=op.f("ck_hadiths_text_hash"),
        ),
        sa.ForeignKeyConstraint(
            ["collection"],
            ["app.hadith_collections.slug"],
            name=op.f("fk_hadiths_collection_hadith_collections"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hadiths")),
        sa.UniqueConstraint("collection", "number", name="uq_hadiths_collection_number"),
        schema="app",
    )
    op.create_table(
        "quran_verses",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("surah", sa.SmallInteger(), nullable=False),
        sa.Column("ayah", sa.SmallInteger(), nullable=False),
        sa.Column("quranpedia_ayah_id", sa.Integer(), nullable=False),
        sa.Column("mushaf_id", sa.SmallInteger(), nullable=False),
        sa.Column("page", sa.SmallInteger(), nullable=False),
        sa.Column("juz", sa.SmallInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("text <> ''", name=op.f("ck_quran_verses_text_not_empty")),
        sa.CheckConstraint(
            "text_sha256 = encode(sha256(convert_to(text, 'UTF8')), 'hex')",
            name=op.f("ck_quran_verses_text_hash"),
        ),
        sa.CheckConstraint("ayah >= 1", name=op.f("ck_quran_verses_ayah_positive")),
        sa.ForeignKeyConstraint(
            ["surah"], ["app.quran_surahs.number"], name=op.f("fk_quran_verses_surah_quran_surahs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quran_verses")),
        sa.UniqueConstraint("quranpedia_ayah_id", name=op.f("uq_quran_verses_quranpedia_ayah_id")),
        sa.UniqueConstraint("surah", "ayah", name="uq_quran_verses_surah_ayah"),
        schema="app",
    )
    op.create_table(
        "hadith_rulings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("hadith_id", sa.BigInteger(), nullable=False),
        sa.Column("ruling_text", sa.Text(), nullable=False),
        sa.Column("scholar", sa.Text(), nullable=False),
        sa.Column("source_book", sa.Text(), nullable=False),
        sa.Column("page", sa.Text(), nullable=False),
        sa.Column("dorar_url", sa.Text(), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("recorded_by", sa.Uuid(), nullable=True),
        sa.Column("editor_name", sa.Text(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "classification IN ('صحيح', 'حسن', 'ضعيف', 'موضوع', 'مختلف_فيه')",
            name=op.f("ck_hadith_rulings_classification"),
        ),
        sa.CheckConstraint(
            "dorar_url LIKE 'https://dorar.net/%'", name=op.f("ck_hadith_rulings_dorar_url")
        ),
        sa.CheckConstraint(
            "editor_name <> ''", name=op.f("ck_hadith_rulings_editor_name_not_empty")
        ),
        sa.CheckConstraint(
            "ruling_text <> ''", name=op.f("ck_hadith_rulings_ruling_text_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["hadith_id"], ["app.hadiths.id"], name=op.f("fk_hadith_rulings_hadith_id_hadiths")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hadith_rulings")),
        schema="app",
    )
    op.create_index(
        "ix_hadith_rulings_hadith_id_recorded_at",
        "hadith_rulings",
        ["hadith_id", "recorded_at"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "hadith_search",
        sa.Column("hadith_id", sa.BigInteger(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hadith_id"],
            ["app.hadiths.id"],
            name=op.f("fk_hadith_search_hadith_id_hadiths"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("hadith_id", name=op.f("pk_hadith_search")),
        schema="app",
    )
    op.create_index(
        "ix_hadith_search_normalized_text_trgm",
        "hadith_search",
        ["normalized_text"],
        unique=False,
        schema="app",
        postgresql_using="gin",
        postgresql_ops={"normalized_text": "gin_trgm_ops"},
    )
    op.create_table(
        "hadith_signals",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("source_record_id", sa.String(length=16), nullable=False),
        sa.Column("hadith_id", sa.BigInteger(), nullable=True),
        sa.Column("match_coverage", sa.Float(), nullable=True),
        sa.Column("matches", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("domain", sa.Text(), nullable=True),
        sa.Column("category_old", sa.Text(), nullable=True),
        sa.Column("category_new", sa.Text(), nullable=True),
        sa.Column("subcategory", sa.Text(), nullable=True),
        sa.Column("semantic_tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("key_concepts", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("topics_for_retrieval", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("sciences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_written_summary", sa.Text(), nullable=True),
        sa.Column("model_written_rephrase", sa.Text(), nullable=True),
        sa.Column("generated_by_model", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hadith_id"], ["app.hadiths.id"], name=op.f("fk_hadith_signals_hadith_id_hadiths")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hadith_signals")),
        sa.UniqueConstraint("source_record_id", name=op.f("uq_hadith_signals_source_record_id")),
        schema="app",
    )
    op.create_index(
        "ix_hadith_signals_hadith_id", "hadith_signals", ["hadith_id"], unique=False, schema="app"
    )
    op.create_table(
        "hadith_verification_queue",
        sa.Column("hadith_id", sa.BigInteger(), nullable=False),
        sa.Column("demand_count", sa.Integer(), nullable=False),
        sa.Column(
            "first_requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hadith_id"],
            ["app.hadiths.id"],
            name=op.f("fk_hadith_verification_queue_hadith_id_hadiths"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("hadith_id", name=op.f("pk_hadith_verification_queue")),
        schema="app",
    )
    op.create_index(
        "ix_hadith_verification_queue_demand_count",
        "hadith_verification_queue",
        ["demand_count"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "quran_annotations",
        sa.Column("surah", sa.SmallInteger(), nullable=False),
        sa.Column("ayah", sa.SmallInteger(), nullable=False),
        sa.Column("source_ayah_id", sa.Integer(), nullable=False),
        sa.Column("islamic_domain", sa.Text(), nullable=True),
        sa.Column("categories", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("key_concepts", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("keywords_ar", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("semantic_tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("annotation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("annotation_model", sa.Text(), nullable=True),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["surah", "ayah"],
            ["app.quran_verses.surah", "app.quran_verses.ayah"],
            name="fk_quran_annotations_surah_ayah_quran_verses",
        ),
        sa.PrimaryKeyConstraint("surah", "ayah", name=op.f("pk_quran_annotations")),
        schema="app",
    )
    op.create_table(
        "quran_verse_history",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("verse_id", sa.BigInteger(), nullable=False),
        sa.Column("surah", sa.SmallInteger(), nullable=False),
        sa.Column("ayah", sa.SmallInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("replaced_by_version", sa.Text(), nullable=False),
        sa.Column(
            "replaced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "text_sha256 = encode(sha256(convert_to(text, 'UTF8')), 'hex')",
            name=op.f("ck_quran_verse_history_text_hash"),
        ),
        sa.ForeignKeyConstraint(
            ["verse_id"],
            ["app.quran_verses.id"],
            name=op.f("fk_quran_verse_history_verse_id_quran_verses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quran_verse_history")),
        schema="app",
    )
    op.create_index(
        "ix_quran_verse_history_verse_id",
        "quran_verse_history",
        ["verse_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "quran_verse_search",
        sa.Column("verse_id", sa.BigInteger(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["verse_id"],
            ["app.quran_verses.id"],
            name=op.f("fk_quran_verse_search_verse_id_quran_verses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("verse_id", name=op.f("pk_quran_verse_search")),
        schema="app",
    )
    op.create_index(
        "ix_quran_verse_search_normalized_text_trgm",
        "quran_verse_search",
        ["normalized_text"],
        unique=False,
        schema="app",
        postgresql_using="gin",
        postgresql_ops={"normalized_text": "gin_trgm_ops"},
    )
    _create_guards()


def downgrade() -> None:
    # Dropping a table drops its triggers; the function they call goes last.
    op.drop_index(
        "ix_quran_verse_search_normalized_text_trgm",
        table_name="quran_verse_search",
        schema="app",
        postgresql_using="gin",
        postgresql_ops={"normalized_text": "gin_trgm_ops"},
    )
    op.drop_table("quran_verse_search", schema="app")
    op.drop_index("ix_quran_verse_history_verse_id", table_name="quran_verse_history", schema="app")
    op.drop_table("quran_verse_history", schema="app")
    op.drop_table("quran_annotations", schema="app")
    op.drop_index(
        "ix_hadith_verification_queue_demand_count",
        table_name="hadith_verification_queue",
        schema="app",
    )
    op.drop_table("hadith_verification_queue", schema="app")
    op.drop_index("ix_hadith_signals_hadith_id", table_name="hadith_signals", schema="app")
    op.drop_table("hadith_signals", schema="app")
    op.drop_index(
        "ix_hadith_search_normalized_text_trgm",
        table_name="hadith_search",
        schema="app",
        postgresql_using="gin",
        postgresql_ops={"normalized_text": "gin_trgm_ops"},
    )
    op.drop_table("hadith_search", schema="app")
    op.drop_index(
        "ix_hadith_rulings_hadith_id_recorded_at", table_name="hadith_rulings", schema="app"
    )
    op.drop_table("hadith_rulings", schema="app")
    op.drop_table("quran_verses", schema="app")
    op.drop_table("hadiths", schema="app")
    op.drop_table("scripture_sync_state", schema="app")
    op.drop_index("ix_scripture_audit_entity_key", table_name="scripture_audit", schema="app")
    op.drop_table("scripture_audit", schema="app")
    op.drop_table("quran_surahs", schema="app")
    op.drop_table("hadith_collections", schema="app")
    op.execute("DROP FUNCTION app.scripture_write_guard()")
