"""create_scan_tables

Revision ID: 20261004_180000
Revises: 20261004_170000
Create Date: 2026-10-04 18:00:00.000000

What the scan workflow keeps for a learner: the guests, the scans, the insights
with their evidence by reference, the three chat messages of an insight, the
places of the world, the threads between them and the hidden treasures.
Everything is owned by an account or a guest and goes with it (ON DELETE
CASCADE). Generated by autogenerate, then edited by hand.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20261004_180000"
down_revision: str | Sequence[str] | None = "20261004_170000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "guests",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(key) = 64", name=op.f("ck_guests_key_length")),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_guests")),
        schema="app",
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_key", sa.String(length=64), nullable=True),
        sa.Column(
            "source",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.String(length=32),
            nullable=True,
        ),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("run", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("engine", sa.String(length=16), nullable=False),
        sa.Column("sensitive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "sensitive_categories",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("image_width", sa.Integer(), nullable=True),
        sa.Column("image_height", sa.Integer(), nullable=True),
        sa.Column("scene", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("focus", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("clarification_question", sa.Text(), nullable=True),
        sa.Column("clarification_answer", sa.Text(), nullable=True),
        sa.Column(
            "awaiting_ruling",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('insights', 'needs_clarification', 'no_relevant_evidence')",
            name=op.f("ck_scans_outcome"),
        ),
        sa.CheckConstraint("source IN ('upload', 'url')", name=op.f("ck_scans_source")),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'done', 'failed')", name=op.f("ck_scans_status")
        ),
        sa.CheckConstraint("num_nonnulls(user_id, guest_key) = 1", name=op.f("ck_scans_one_owner")),
        sa.CheckConstraint("run >= 1", name=op.f("ck_scans_run_positive")),
        sa.ForeignKeyConstraint(
            ["guest_key"],
            ["app.guests.key"],
            name=op.f("fk_scans_guest_key_guests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app.users.id"], name=op.f("fk_scans_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scans")),
        schema="app",
    )
    op.create_index(
        "ix_scans_guest_key_created_at",
        "scans",
        ["guest_key", "created_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_scans_user_id_created_at",
        "scans",
        ["user_id", "created_at"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "world_places",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_key", sa.String(length=64), nullable=True),
        sa.Column("region_id", sa.String(length=16), nullable=False),
        sa.Column("regions_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_visited_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "num_nonnulls(user_id, guest_key) = 1", name=op.f("ck_world_places_one_owner")
        ),
        sa.ForeignKeyConstraint(
            ["guest_key"],
            ["app.guests.key"],
            name=op.f("fk_world_places_guest_key_guests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_world_places_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_world_places")),
        schema="app",
    )
    op.create_index(
        "uq_world_places_guest_region",
        "world_places",
        ["guest_key", "region_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("guest_key IS NOT NULL"),
    )
    op.create_index(
        "uq_world_places_user_region",
        "world_places",
        ["user_id", "region_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "insights",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_key", sa.String(length=64), nullable=True),
        sa.Column("scan_id", sa.Uuid(), nullable=True),
        sa.Column(
            "origin",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column("tutorial_scene", sa.String(length=64), nullable=True),
        sa.Column("tutorial_slug", sa.String(length=64), nullable=True),
        sa.Column("run", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("position", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("engine", sa.String(length=16), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("glimpse", sa.Text(), nullable=False),
        sa.Column(
            "entity_ids",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "action_ids",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("anchor", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("relation", sa.String(length=32), nullable=False),
        sa.Column("quran_surah", sa.SmallInteger(), nullable=True),
        sa.Column("quran_ayah", sa.SmallInteger(), nullable=True),
        sa.Column("quran_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hadith_collection", sa.String(length=32), nullable=True),
        sa.Column("hadith_number", sa.String(length=32), nullable=True),
        sa.Column("hadith_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("why", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("small_step", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("learning_unit_id", sa.String(length=16), nullable=True),
        sa.Column("learning_path_version", sa.String(length=64), nullable=True),
        sa.Column(
            "action_state",
            sa.String(length=32),
            nullable=True,
        ),
        sa.Column("action_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("place_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(origin = 'scan') = (scan_id IS NOT NULL)",
            name=op.f("ck_insights_scan_insight_has_a_scan"),
        ),
        sa.CheckConstraint(
            "(origin = 'tutorial') = (tutorial_slug IS NOT NULL)",
            name=op.f("ck_insights_tutorial_insight_has_a_slug"),
        ),
        sa.CheckConstraint(
            "action_state IN ('done', 'later')", name=op.f("ck_insights_action_state")
        ),
        sa.CheckConstraint("origin IN ('scan', 'tutorial')", name=op.f("ck_insights_origin")),
        sa.CheckConstraint(
            "(hadith_collection IS NULL) = (hadith_number IS NULL)",
            name=op.f("ck_insights_hadith_reference_whole"),
        ),
        sa.CheckConstraint(
            "(quran_surah IS NULL) = (quran_ayah IS NULL)",
            name=op.f("ck_insights_quran_reference_whole"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(user_id, guest_key) = 1", name=op.f("ck_insights_one_owner")
        ),
        sa.ForeignKeyConstraint(
            ["guest_key"],
            ["app.guests.key"],
            name=op.f("fk_insights_guest_key_guests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["app.world_places.id"],
            name=op.f("fk_insights_place_id_world_places"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["app.scans.id"],
            name=op.f("fk_insights_scan_id_scans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_insights_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insights")),
        schema="app",
    )
    op.create_index(
        "ix_insights_guest_key_completed_at",
        "insights",
        ["guest_key", "completed_at"],
        unique=False,
        schema="app",
    )
    op.create_index("ix_insights_scan_id", "insights", ["scan_id"], unique=False, schema="app")
    op.create_index(
        "ix_insights_user_id_completed_at",
        "insights",
        ["user_id", "completed_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "uq_insights_guest_tutorial",
        "insights",
        ["guest_key", "tutorial_scene", "tutorial_slug"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("guest_key IS NOT NULL AND tutorial_slug IS NOT NULL"),
    )
    op.create_index(
        "uq_insights_user_tutorial",
        "insights",
        ["user_id", "tutorial_scene", "tutorial_slug"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("user_id IS NOT NULL AND tutorial_slug IS NOT NULL"),
    )
    op.create_table(
        "insight_chat_messages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("insight_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("level", sa.String(length=1), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "level IS NULL OR level IN ('a', 'b', 'c', 'd')",
            name=op.f("ck_insight_chat_messages_level"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'answered')", name=op.f("ck_insight_chat_messages_status")
        ),
        sa.ForeignKeyConstraint(
            ["insight_id"],
            ["app.insights.id"],
            name=op.f("fk_insight_chat_messages_insight_id_insights"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insight_chat_messages")),
        sa.UniqueConstraint(
            "insight_id", "idempotency_key", name="uq_insight_chat_messages_idempotency_key"
        ),
        schema="app",
    )
    op.create_index(
        "ix_insight_chat_messages_insight_id",
        "insight_chat_messages",
        ["insight_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "treasures",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("insight_id", sa.Uuid(), nullable=False),
        sa.Column("place_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column("quran_surah", sa.SmallInteger(), nullable=True),
        sa.Column("quran_ayah", sa.SmallInteger(), nullable=True),
        sa.Column("hadith_collection", sa.String(length=32), nullable=True),
        sa.Column("hadith_number", sa.String(length=32), nullable=True),
        sa.Column("learning_unit_id", sa.String(length=16), nullable=False),
        sa.Column("learning_path_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('alternative', 'deeper')", name=op.f("ck_treasures_kind")),
        sa.CheckConstraint(
            "(hadith_collection IS NULL) = (hadith_number IS NULL)",
            name=op.f("ck_treasures_hadith_reference_whole"),
        ),
        sa.CheckConstraint(
            "(quran_surah IS NULL) = (quran_ayah IS NULL)",
            name=op.f("ck_treasures_quran_reference_whole"),
        ),
        sa.CheckConstraint(
            "quran_surah IS NOT NULL OR hadith_collection IS NOT NULL",
            name=op.f("ck_treasures_has_evidence"),
        ),
        sa.ForeignKeyConstraint(
            ["insight_id"],
            ["app.insights.id"],
            name=op.f("fk_treasures_insight_id_insights"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["app.world_places.id"],
            name=op.f("fk_treasures_place_id_world_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treasures")),
        sa.UniqueConstraint("insight_id", name="uq_treasures_insight_id"),
        schema="app",
    )
    op.create_index("ix_treasures_place_id", "treasures", ["place_id"], unique=False, schema="app")
    op.create_table(
        "world_relations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("place_a_id", sa.Uuid(), nullable=False),
        sa.Column("place_b_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column("insight_a_id", sa.Uuid(), nullable=False),
        sa.Column("insight_b_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('same_scene', 'prerequisite')", name=op.f("ck_world_relations_reason")
        ),
        sa.CheckConstraint(
            "place_a_id < place_b_id", name=op.f("ck_world_relations_places_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["insight_a_id"],
            ["app.insights.id"],
            name=op.f("fk_world_relations_insight_a_id_insights"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["insight_b_id"],
            ["app.insights.id"],
            name=op.f("fk_world_relations_insight_b_id_insights"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["place_a_id"],
            ["app.world_places.id"],
            name=op.f("fk_world_relations_place_a_id_world_places"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["place_b_id"],
            ["app.world_places.id"],
            name=op.f("fk_world_relations_place_b_id_world_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_world_relations")),
        sa.UniqueConstraint(
            "place_a_id", "place_b_id", "reason", name="uq_world_relations_places_reason"
        ),
        schema="app",
    )
    op.create_index(
        "ix_world_relations_place_b_id",
        "world_relations",
        ["place_b_id"],
        unique=False,
        schema="app",
    )


def downgrade() -> None:
    op.drop_index("ix_world_relations_place_b_id", table_name="world_relations", schema="app")
    op.drop_table("world_relations", schema="app")
    op.drop_index("ix_treasures_place_id", table_name="treasures", schema="app")
    op.drop_table("treasures", schema="app")
    op.drop_index(
        "ix_insight_chat_messages_insight_id", table_name="insight_chat_messages", schema="app"
    )
    op.drop_table("insight_chat_messages", schema="app")
    op.drop_index(
        "uq_insights_user_tutorial",
        table_name="insights",
        schema="app",
        postgresql_where=sa.text("user_id IS NOT NULL AND tutorial_slug IS NOT NULL"),
    )
    op.drop_index(
        "uq_insights_guest_tutorial",
        table_name="insights",
        schema="app",
        postgresql_where=sa.text("guest_key IS NOT NULL AND tutorial_slug IS NOT NULL"),
    )
    op.drop_index("ix_insights_user_id_completed_at", table_name="insights", schema="app")
    op.drop_index("ix_insights_scan_id", table_name="insights", schema="app")
    op.drop_index("ix_insights_guest_key_completed_at", table_name="insights", schema="app")
    op.drop_table("insights", schema="app")
    op.drop_index(
        "uq_world_places_user_region",
        table_name="world_places",
        schema="app",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_world_places_guest_region",
        table_name="world_places",
        schema="app",
        postgresql_where=sa.text("guest_key IS NOT NULL"),
    )
    op.drop_table("world_places", schema="app")
    op.drop_index("ix_scans_user_id_created_at", table_name="scans", schema="app")
    op.drop_index("ix_scans_guest_key_created_at", table_name="scans", schema="app")
    op.drop_table("scans", schema="app")
    op.drop_table("guests", schema="app")
