"""add_scripture_search_vectors

Revision ID: 20261004_193000
Revises: 20261004_192500
Create Date: 2026-10-04 19:30:00.000000

A full-text vector on each search copy of the scripture store, computed by the
database from the copy, with its GIN index: the lexical half of the insight
engine's hybrid search. The embeddings themselves live in the `vectors` chain
(decision 48). Generated by autogenerate, the two tables folded into a loop.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20261004_193000"
down_revision: str | Sequence[str] | None = "20261004_192500"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SEARCH_TABLES = ("quran_verse_search", "hadith_search")
SEARCH_VECTOR = "to_tsvector('simple'::regconfig, normalized_text)"


def upgrade() -> None:
    for table in SEARCH_TABLES:
        op.add_column(
            table,
            sa.Column(
                "search_vector",
                postgresql.TSVECTOR(),
                sa.Computed(SEARCH_VECTOR, persisted=True),
                nullable=False,
            ),
            schema="app",
        )
        op.create_index(
            f"ix_{table}_search_vector",
            table,
            ["search_vector"],
            unique=False,
            schema="app",
            postgresql_using="gin",
        )


def downgrade() -> None:
    for table in SEARCH_TABLES:
        op.drop_index(f"ix_{table}_search_vector", table_name=table, schema="app")
        op.drop_column(table, "search_vector", schema="app")
