"""create_social_network_tables

Revision ID: 20261004_170000
Revises: 20261004_160000
Create Date: 2026-10-04 17:00:00.000000

The social network («تبصرة تواصل»): a public handle and name on the account, follows,
blocks, the immutable insight publications, posts, likes, bookmarks, comments, reports
and the moderation log. Generated by autogenerate, then edited by hand: the enum columns
are text with a named CHECK like the other tables; a trigger makes a publication
immutable; the moderation log is a TimescaleDB hypertable (decision 13) with a trigger
that refuses UPDATE and DELETE and compression and retention policies from the settings.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from src.config import get_settings

revision: str = "20261004_170000"
down_revision: str | Sequence[str] | None = "20261004_160000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "app"
MODERATION_TABLE = "app.moderation_actions"
# The handle format, written out here so the migration never changes with the model.
HANDLE_PATTERN = r"^[A-Za-z\u0621-\u063A\u0641-\u064A][A-Za-z0-9_\u0621-\u063A\u0641-\u064A]{2,29}$"


# Both lists are JSON arrays and together hold at least one reference. CASE keeps the length
# call from running on a value that is not an array.
EVIDENCE_CHECK = (
    "CASE WHEN jsonb_typeof(quran_refs) = 'array' AND jsonb_typeof(hadith_refs) = 'array' "
    "THEN jsonb_array_length(quran_refs) + jsonb_array_length(hadith_refs) >= 1 "
    "ELSE false END"
)


def _uuid_pk() -> sa.Column[sa.Uuid]:
    return sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False)


def _created_at(name: str = "created_at") -> sa.Column[sa.DateTime]:
    return sa.Column(
        name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    )


def _one_of(table: str, column: str, values: Sequence[str]) -> sa.CheckConstraint:
    """Limit a text column to a list, with the constraint name the models use."""
    listed = ", ".join(f"'{value}'" for value in values)
    return sa.CheckConstraint(f"{column} IN ({listed})", name=op.f(f"ck_{table}_{column}"))


def upgrade() -> None:
    settings = get_settings()

    op.add_column("users", sa.Column("handle", sa.String(length=30), nullable=True), schema=SCHEMA)
    op.add_column(
        "users", sa.Column("public_name", sa.String(length=40), nullable=True), schema=SCHEMA
    )
    op.create_check_constraint(
        op.f("ck_users_handle_format"), "users", f"handle ~ '{HANDLE_PATTERN}'", schema=SCHEMA
    )
    op.create_index(
        "uq_users_handle_lower",
        "users",
        [sa.literal_column("lower(handle)")],
        unique=True,
        schema=SCHEMA,
    )

    op.create_table(
        "follows",
        sa.Column("follower_id", sa.Uuid(), nullable=False),
        sa.Column("followee_id", sa.Uuid(), nullable=False),
        _created_at(),
        sa.CheckConstraint("follower_id <> followee_id", name=op.f("ck_follows_no_self_follow")),
        sa.ForeignKeyConstraint(
            ["followee_id"],
            ["app.users.id"],
            name=op.f("fk_follows_followee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["app.users.id"],
            name=op.f("fk_follows_follower_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("follower_id", "followee_id", name="pk_follows"),
        schema=SCHEMA,
    )
    op.create_index("ix_follows_followee_id", "follows", ["followee_id"], schema=SCHEMA)

    op.create_table(
        "blocks",
        sa.Column("blocker_id", sa.Uuid(), nullable=False),
        sa.Column("blocked_id", sa.Uuid(), nullable=False),
        _created_at(),
        sa.CheckConstraint("blocker_id <> blocked_id", name=op.f("ck_blocks_no_self_block")),
        sa.ForeignKeyConstraint(
            ["blocked_id"],
            ["app.users.id"],
            name=op.f("fk_blocks_blocked_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["blocker_id"],
            ["app.users.id"],
            name=op.f("fk_blocks_blocker_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("blocker_id", "blocked_id", name="pk_blocks"),
        schema=SCHEMA,
    )
    op.create_index("ix_blocks_blocked_id", "blocks", ["blocked_id"], schema=SCHEMA)

    op.create_table(
        "insight_publications",
        _uuid_pk(),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("insight_id", sa.Uuid(), nullable=False),
        sa.Column("insight_version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("glimpse", sa.String(length=600), nullable=False),
        sa.Column("relation_type", sa.String(length=32), nullable=False),
        sa.Column(
            "concepts",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("quran_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hadith_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation_excerpt", sa.String(length=1200), nullable=False),
        sa.Column("step_text", sa.String(length=400), nullable=True),
        sa.Column("photo_ref", sa.String(length=512), nullable=True),
        _created_at(),
        sa.CheckConstraint(
            EVIDENCE_CHECK,
            name=op.f("ck_insight_publications_has_evidence"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["app.users.id"],
            name=op.f("fk_insight_publications_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insight_publications")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_insight_publications_author_id_created_at",
        "insight_publications",
        ["author_id", "created_at"],
        schema=SCHEMA,
    )
    op.create_index(
        "ix_insight_publications_insight_id", "insight_publications", ["insight_id"], schema=SCHEMA
    )
    # A copy that is published is never edited; a DELETE (the author's, or their account's
    # cascade) is not an update and is not refused.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION app.insight_publications_forbid_update() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'insight publications are immutable'
                USING ERRCODE = 'integrity_constraint_violation';
        END
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER insight_publications_forbid_update BEFORE UPDATE ON app.insight_publications
        FOR EACH ROW EXECUTE FUNCTION app.insight_publications_forbid_update()
        """
    )

    op.create_table(
        "posts",
        _uuid_pk(),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("publication_id", sa.Uuid(), nullable=True),
        sa.Column("reflection", sa.String(length=800), nullable=True),
        sa.Column(
            "reflection_looks_like_scripture",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("visibility", sa.String(length=32), server_default="public", nullable=False),
        sa.Column("status", sa.String(length=32), server_default="draft", nullable=False),
        sa.Column("status_reason", sa.String(length=64), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removal_source", sa.String(length=32), nullable=True),
        _created_at(),
        _created_at("updated_at"),
        _one_of("posts", "visibility", ("public", "followers")),
        _one_of("posts", "status", ("draft", "pending_review", "published", "rejected", "removed")),
        _one_of("posts", "removal_source", ("owner", "moderator")),
        sa.CheckConstraint(
            "status <> 'published' OR published_at IS NOT NULL",
            name=op.f("ck_posts_published_has_time"),
        ),
        sa.CheckConstraint(
            "status <> 'removed' OR removal_source IS NOT NULL",
            name=op.f("ck_posts_removed_has_source"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["app.users.id"],
            name=op.f("fk_posts_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["app.insight_publications.id"],
            name=op.f("fk_posts_publication_id_insight_publications"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
        sa.UniqueConstraint("publication_id", name=op.f("uq_posts_publication_id")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_posts_public_feed",
        "posts",
        [sa.literal_column("published_at DESC"), sa.literal_column("id DESC")],
        schema=SCHEMA,
        postgresql_where=sa.text("status = 'published' AND visibility = 'public'"),
    )
    op.create_index(
        "ix_posts_author_feed",
        "posts",
        ["author_id", sa.literal_column("published_at DESC"), sa.literal_column("id DESC")],
        schema=SCHEMA,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_index(
        "ix_posts_author_id_created_at",
        "posts",
        ["author_id", sa.literal_column("created_at DESC")],
        schema=SCHEMA,
    )
    op.create_index(
        "ix_posts_pending_review",
        "posts",
        ["created_at"],
        schema=SCHEMA,
        postgresql_where=sa.text("status = 'pending_review'"),
    )

    op.create_table(
        "post_likes",
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        _created_at(),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["app.posts.id"],
            name=op.f("fk_post_likes_post_id_posts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_post_likes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("post_id", "user_id", name="pk_post_likes"),
        schema=SCHEMA,
    )
    op.create_index("ix_post_likes_user_id", "post_likes", ["user_id"], schema=SCHEMA)

    op.create_table(
        "bookmarks",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        _created_at(),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["app.posts.id"],
            name=op.f("fk_bookmarks_post_id_posts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_bookmarks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "post_id", name="pk_bookmarks"),
        schema=SCHEMA,
    )
    op.create_index("ix_bookmarks_post_id", "bookmarks", ["post_id"], schema=SCHEMA)
    op.create_index(
        "ix_bookmarks_user_id_created_at",
        "bookmarks",
        ["user_id", sa.literal_column("created_at DESC")],
        schema=SCHEMA,
    )

    op.create_table(
        "comments",
        _uuid_pk(),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending_review", nullable=False),
        sa.Column("status_reason", sa.String(length=64), nullable=True),
        _created_at(),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        _one_of("comments", "status", ("pending_review", "published", "rejected", "removed")),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["app.users.id"],
            name=op.f("fk_comments_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["app.comments.id"],
            name=op.f("fk_comments_parent_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["app.posts.id"],
            name=op.f("fk_comments_post_id_posts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_comments_post_id_created_at", "comments", ["post_id", "created_at", "id"], schema=SCHEMA
    )
    op.create_index("ix_comments_parent_id", "comments", ["parent_id"], schema=SCHEMA)
    op.create_index("ix_comments_author_id", "comments", ["author_id"], schema=SCHEMA)
    op.create_index(
        "ix_comments_pending_review",
        "comments",
        ["created_at"],
        schema=SCHEMA,
        postgresql_where=sa.text("status = 'pending_review'"),
    )

    op.create_table(
        "reports",
        _uuid_pk(),
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("details", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="open", nullable=False),
        _created_at(),
        sa.Column("handled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handled_by", sa.Uuid(), nullable=True),
        _one_of("reports", "target_type", ("post", "comment")),
        _one_of(
            "reports",
            "reason",
            (
                "abuse",
                "spam",
                "false_religious_claim",
                "unauthorised_photo",
                "wrong_place",
                "private_information",
                "other",
            ),
        ),
        _one_of("reports", "status", ("open", "actioned", "dismissed")),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["app.users.id"],
            name=op.f("fk_reports_reporter_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        schema=SCHEMA,
    )
    op.create_index(
        "uq_reports_reporter_target",
        "reports",
        ["reporter_id", "target_type", "target_id"],
        unique=True,
        schema=SCHEMA,
    )
    op.create_index("ix_reports_target", "reports", ["target_type", "target_id"], schema=SCHEMA)
    op.create_index(
        "ix_reports_open",
        "reports",
        ["created_at"],
        schema=SCHEMA,
        postgresql_where=sa.text("status = 'open'"),
    )

    op.create_table(
        "moderation_actions",
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        _one_of("moderation_actions", "target_type", ("post", "comment")),
        _one_of(
            "moderation_actions",
            "action",
            ("published", "held", "rejected", "removed", "restored", "withdrawn"),
        ),
        _one_of("moderation_actions", "source", ("guard", "moderator", "reports", "owner")),
        sa.PrimaryKeyConstraint("at", "id", name="pk_moderation_actions"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_moderation_actions_target_at",
        "moderation_actions",
        ["target_type", "target_id", "at"],
        schema=SCHEMA,
    )
    op.execute(
        f"""
        SELECT create_hypertable(
            '{MODERATION_TABLE}', by_range('at', INTERVAL '7 days'),
            create_default_indexes => false
        )
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION app.moderation_actions_forbid_change() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'the moderation log is append-only'
                USING ERRCODE = 'integrity_constraint_violation';
        END
        $$
        """
    )
    op.execute(
        f"""
        CREATE TRIGGER moderation_actions_forbid_change BEFORE UPDATE OR DELETE ON {MODERATION_TABLE}
        FOR EACH ROW EXECUTE FUNCTION app.moderation_actions_forbid_change()
        """
    )
    op.execute(
        f"""
        ALTER TABLE {MODERATION_TABLE} SET (
            timescaledb.compress,
            timescaledb.compress_segmentby = 'target_type',
            timescaledb.compress_orderby = 'at DESC, id DESC'
        )
        """
    )
    compress_after = int(settings.moderation_log_compress_after_days)
    retention = int(settings.moderation_log_retention_days)
    op.execute(
        f"SELECT add_compression_policy('{MODERATION_TABLE}', INTERVAL '{compress_after} days')"
    )
    op.execute(f"SELECT add_retention_policy('{MODERATION_TABLE}', INTERVAL '{retention} days')")


def downgrade() -> None:
    # Dropping the hypertable drops its chunks, its trigger and its two policies.
    op.drop_table("moderation_actions", schema=SCHEMA)
    op.execute("DROP FUNCTION app.moderation_actions_forbid_change()")
    op.drop_table("reports", schema=SCHEMA)
    op.drop_table("comments", schema=SCHEMA)
    op.drop_table("bookmarks", schema=SCHEMA)
    op.drop_table("post_likes", schema=SCHEMA)
    op.drop_table("posts", schema=SCHEMA)
    # Dropping the table drops its trigger; the function it called stays until here.
    op.drop_table("insight_publications", schema=SCHEMA)
    op.execute("DROP FUNCTION app.insight_publications_forbid_update()")
    op.drop_table("blocks", schema=SCHEMA)
    op.drop_table("follows", schema=SCHEMA)
    op.drop_index("uq_users_handle_lower", table_name="users", schema=SCHEMA)
    op.drop_constraint(op.f("ck_users_handle_format"), "users", schema=SCHEMA)
    op.drop_column("users", "public_name", schema=SCHEMA)
    op.drop_column("users", "handle", schema=SCHEMA)
