"""create_cookie_consents

Revision ID: 20261004_123000
Revises: 20261004_121500
Create Date: 2026-10-04 12:30:00.000000

Proof of cookie consent (decision 32): one append-only row per choice a visitor
made, under an anonymous consent id, with the policy version, each category and
the browser family. Generated by autogenerate, then edited by hand: the guard
function and its triggers are added, which autogenerate cannot see. The guard
SQL is the same as in src/models/cookie_consent.py.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20261004_123000"
down_revision: str | Sequence[str] | None = "20261004_121500"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

GUARD_FUNCTION = """
CREATE OR REPLACE FUNCTION app.cookie_consents_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.user_id IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM app.users WHERE id = OLD.user_id) THEN
            RETURN OLD;
        END IF;
    END IF;
    RAISE EXCEPTION 'cookie_consents is append-only: % refused', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END
$$
"""
GUARD_TRIGGERS = (
    """
    CREATE TRIGGER cookie_consents_row_guard BEFORE UPDATE OR DELETE ON app.cookie_consents
    FOR EACH ROW EXECUTE FUNCTION app.cookie_consents_guard()
    """,
    """
    CREATE TRIGGER cookie_consents_truncate_guard BEFORE TRUNCATE ON app.cookie_consents
    FOR EACH STATEMENT EXECUTE FUNCTION app.cookie_consents_guard()
    """,
)


def upgrade() -> None:
    op.create_table(
        "cookie_consents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("consent_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("necessary", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("analytics", sa.Boolean(), nullable=False),
        sa.Column("behaviour", sa.Boolean(), nullable=False),
        sa.Column("user_agent_family", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "user_agent_family IN ('chrome', 'edge', 'firefox', 'opera', 'other', 'safari', "
            "'samsung_internet')",
            name=op.f("ck_cookie_consents_user_agent_family_known"),
        ),
        sa.CheckConstraint("necessary", name=op.f("ck_cookie_consents_necessary_always_on")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_cookie_consents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cookie_consents")),
        schema="app",
    )
    op.create_index(
        "ix_cookie_consents_consent_id_created_at",
        "cookie_consents",
        ["consent_id", "created_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_cookie_consents_user_id", "cookie_consents", ["user_id"], unique=False, schema="app"
    )
    # Append-only: a choice is never edited or removed. Its rows leave only with their
    # user, whose deletion cascades to them.
    op.execute(GUARD_FUNCTION)
    for trigger in GUARD_TRIGGERS:
        op.execute(trigger)


def downgrade() -> None:
    # The table goes first, with its triggers; the function they call goes after.
    op.drop_index("ix_cookie_consents_user_id", table_name="cookie_consents", schema="app")
    op.drop_index(
        "ix_cookie_consents_consent_id_created_at", table_name="cookie_consents", schema="app"
    )
    op.drop_table("cookie_consents", schema="app")
    op.execute("DROP FUNCTION IF EXISTS app.cookie_consents_guard()")
