"""create_retrieval_tables

Revision ID: 20261004_193000
Revises: 20261004_192500
Create Date: 2026-10-04 19:30:00.000000

The vectors of the scripture store, one row per text and embedding model, the
runs of `src.cli.embed_corpus` with what they cost, and a full-text vector on
each search copy, computed by the database, with its GIN index. Each
provider's default embedding (docs/BENCHMARK.md) gets a partial HNSW index on
the vector cast to its size. Generated by autogenerate, the two search-vector
columns and the four HNSW indexes folded into loops.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20261004_193000"
down_revision: str | Sequence[str] | None = "20261004_192500"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SEARCH_TABLES = ("quran_verse_search", "hadith_search")
SEARCH_VECTOR = "to_tsvector('simple'::regconfig, normalized_text)"
EMBEDDING_TABLES = ("quran_verse_embeddings", "hadith_embeddings")
INDEXED_EMBEDDINGS = (("text-embedding-3-large", 1536), ("bge-m3", 1024))


def _create_hnsw_indexes() -> None:
    for table in EMBEDDING_TABLES:
        for model, dimensions in INDEXED_EMBEDDINGS:
            slug = model.replace("-", "_").replace(".", "_")
            op.create_index(
                f"ix_{table}_hnsw_{slug}_{dimensions}",
                table,
                [sa.literal_column(f"(embedding::vector({dimensions})) vector_cosine_ops")],
                unique=False,
                schema="app",
                postgresql_using="hnsw",
                postgresql_where=sa.text(f"model = '{model}' AND dimensions = {dimensions}"),
            )


def upgrade() -> None:
    for table in SEARCH_TABLES:
        op.add_column(
            table,
            sa.Column(
                "search_vector",
                postgresql.TSVECTOR(),
                sa.Computed(SEARCH_VECTOR, persisted=True),
                nullable=False,
            ),
            schema="app",
        )
        op.create_index(
            f"ix_{table}_search_vector",
            table,
            ["search_vector"],
            unique=False,
            schema="app",
            postgresql_using="gin",
        )
    op.create_table(
        "embedding_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("corpus", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("dimensions", sa.SmallInteger(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column("documents", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("unchanged", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("embedded", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("batches", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("corpus IN ('quran', 'hadith')", name=op.f("ck_embedding_runs_corpus")),
        sa.CheckConstraint(
            "status IN ('running', 'done', 'failed')", name=op.f("ck_embedding_runs_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embedding_runs")),
        schema="app",
    )
    op.create_index(
        "ix_embedding_runs_started_at", "embedding_runs", ["started_at"], unique=False, schema="app"
    )
    op.create_table(
        "hadith_embeddings",
        sa.Column("hadith_id", sa.BigInteger(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("dimensions", sa.SmallInteger(), nullable=False),
        sa.Column("document_sha256", sa.String(length=64), nullable=False),
        sa.Column("embedding", VECTOR(), nullable=False),
        sa.Column(
            "embedded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dimensions BETWEEN 1 AND 2000", name=op.f("ck_hadith_embeddings_dimensions_range")
        ),
        sa.CheckConstraint(
            "vector_dims(embedding) = dimensions",
            name=op.f("ck_hadith_embeddings_dimensions_match"),
        ),
        sa.ForeignKeyConstraint(
            ["hadith_id"],
            ["app.hadiths.id"],
            name=op.f("fk_hadith_embeddings_hadith_id_hadiths"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "hadith_id", "model", "dimensions", name=op.f("pk_hadith_embeddings")
        ),
        schema="app",
    )
    op.create_index(
        "ix_hadith_embeddings_model_dimensions",
        "hadith_embeddings",
        ["model", "dimensions"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "quran_verse_embeddings",
        sa.Column("verse_id", sa.BigInteger(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("dimensions", sa.SmallInteger(), nullable=False),
        sa.Column("document_sha256", sa.String(length=64), nullable=False),
        sa.Column("embedding", VECTOR(), nullable=False),
        sa.Column(
            "embedded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dimensions BETWEEN 1 AND 2000", name=op.f("ck_quran_verse_embeddings_dimensions_range")
        ),
        sa.CheckConstraint(
            "vector_dims(embedding) = dimensions",
            name=op.f("ck_quran_verse_embeddings_dimensions_match"),
        ),
        sa.ForeignKeyConstraint(
            ["verse_id"],
            ["app.quran_verses.id"],
            name=op.f("fk_quran_verse_embeddings_verse_id_quran_verses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "verse_id", "model", "dimensions", name=op.f("pk_quran_verse_embeddings")
        ),
        schema="app",
    )
    op.create_index(
        "ix_quran_verse_embeddings_model_dimensions",
        "quran_verse_embeddings",
        ["model", "dimensions"],
        unique=False,
        schema="app",
    )
    _create_hnsw_indexes()


def downgrade() -> None:
    op.drop_index(
        "ix_quran_verse_embeddings_model_dimensions",
        table_name="quran_verse_embeddings",
        schema="app",
    )
    op.drop_table("quran_verse_embeddings", schema="app")
    op.drop_index(
        "ix_hadith_embeddings_model_dimensions", table_name="hadith_embeddings", schema="app"
    )
    op.drop_table("hadith_embeddings", schema="app")
    op.drop_index("ix_embedding_runs_started_at", table_name="embedding_runs", schema="app")
    op.drop_table("embedding_runs", schema="app")
    for table in SEARCH_TABLES:
        op.drop_index(f"ix_{table}_search_vector", table_name=table, schema="app")
        op.drop_column(table, "search_vector", schema="app")
