"""create_learning_tables

Revision ID: 20261004_120000
Revises: 20261004_110000
Create Date: 2026-10-04 12:00:00.000000

The learning path as versioned data (a version, its domains and units) and the
learner's state per unit. Generated by autogenerate, then edited by hand.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20261004_120000"
down_revision: str | Sequence[str] | None = "20261004_110000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "learning_path_versions",
        sa.Column("path_version", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("released_on", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_file", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("domain_count", sa.Integer(), nullable=False),
        sa.Column("unit_count", sa.Integer(), nullable=False),
        sa.Column("depths", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("path_version", name=op.f("pk_learning_path_versions")),
        schema="app",
    )
    op.create_index(
        "uq_learning_path_versions_active",
        "learning_path_versions",
        ["is_active"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "learning_domains",
        sa.Column("path_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("function", sa.Text(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("concepts", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.CheckConstraint("position >= 1", name=op.f("ck_learning_domains_position_positive")),
        sa.ForeignKeyConstraint(
            ["path_version"],
            ["app.learning_path_versions.path_version"],
            name=op.f("fk_learning_domains_path_version_learning_path_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("path_version", "id", name=op.f("pk_learning_domains")),
        sa.UniqueConstraint("path_version", "position", name="uq_learning_domains_position"),
        schema="app",
    )
    op.create_table(
        "learning_units",
        sa.Column("path_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("domain_id", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("objectives", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("prerequisites", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("depths", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("concepts", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("evidence_refs", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("source_anchors", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.CheckConstraint("position >= 1", name=op.f("ck_learning_units_position_positive")),
        sa.ForeignKeyConstraint(
            ["path_version", "domain_id"],
            ["app.learning_domains.path_version", "app.learning_domains.id"],
            name="fk_learning_units_domain",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("path_version", "id", name=op.f("pk_learning_units")),
        sa.UniqueConstraint(
            "path_version", "domain_id", "position", name="uq_learning_units_position"
        ),
        schema="app",
    )
    op.create_index(
        "ix_learning_units_domain",
        "learning_units",
        ["path_version", "domain_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "learner_unit_states",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_key", sa.String(length=64), nullable=True),
        sa.Column("path_version", sa.String(length=64), nullable=False),
        sa.Column("unit_id", sa.String(length=16), nullable=False),
        sa.Column(
            "seen_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Times an insight of this unit was shown.",
        ),
        sa.Column(
            "opened_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Times the learner opened it or one of its sources.",
        ),
        sa.Column(
            "completed_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Times the learner pressed done on an insight of this unit: completion, never mastery.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "char_length(guest_key) >= 16",
            name=op.f("ck_learner_unit_states_guest_key_length"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(user_id, guest_key) = 1", name=op.f("ck_learner_unit_states_one_owner")
        ),
        sa.CheckConstraint(
            "seen_count >= 0 AND opened_count >= 0 AND completed_count >= 0",
            name=op.f("ck_learner_unit_states_counts_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["path_version", "unit_id"],
            ["app.learning_units.path_version", "app.learning_units.id"],
            name="fk_learner_unit_states_unit",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_learner_unit_states_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learner_unit_states")),
        schema="app",
    )
    op.create_index(
        "ix_learner_unit_states_unit",
        "learner_unit_states",
        ["path_version", "unit_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "uq_learner_unit_states_guest",
        "learner_unit_states",
        ["guest_key", "path_version", "unit_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("guest_key IS NOT NULL"),
    )
    op.create_index(
        "uq_learner_unit_states_user",
        "learner_unit_states",
        ["user_id", "path_version", "unit_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index(
        "uq_learner_unit_states_user",
        table_name="learner_unit_states",
        schema="app",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_learner_unit_states_guest",
        table_name="learner_unit_states",
        schema="app",
        postgresql_where=sa.text("guest_key IS NOT NULL"),
    )
    op.drop_index("ix_learner_unit_states_unit", table_name="learner_unit_states", schema="app")
    op.drop_table("learner_unit_states", schema="app")
    op.drop_index("ix_learning_units_domain", table_name="learning_units", schema="app")
    op.drop_table("learning_units", schema="app")
    op.drop_table("learning_domains", schema="app")
    op.drop_index(
        "uq_learning_path_versions_active",
        table_name="learning_path_versions",
        schema="app",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("learning_path_versions", schema="app")
